### PR TITLE
Beam size 1 new path

### PR DESCRIPTION
**Pull request by coder1729**
This addresses the TODO in translator.py +391
# TODO: faster code path for beam_size == 1.
Verified with the old code path with '--fast --beam_size 1' option gives same result

### CODE REVIEW

**Comment by guillaumekln** [comment]
I think it's good to have a fast path for this case (e.g. for back translation). However, this looks like too much code duplication to me.

Can we find a way to nicely support different decoding strategies? This requires some design effort though.

**Comment by vince62s** [comment]
I agree, that's why I wanted a second opinion.

**Comment by coder1729** [comment]
@guillaumekln  sure, could you please elaborate more on what you mean by the above ? Thanks

**Comment by coder1729** [comment]
Also @vince62s  could you also point me to some of the PRs/issues where i can contribute please?

**Comment by daphnei** [comment]
I have some alternative code that both improves the beam_size=1 code path and adds in random sampling as a beam search alternative. I think it is a bit more succinct. I just submitted the pull request here: https://github.com/OpenNMT/OpenNMT-py/pull/1157

**Comment by vince62s** [comment]
@coder1729 see #1158 would be very helpful.

**Pull request closed without merging**
