### PR TITLE
Change map_location to be 'cpu'

### PR DESCRIPTION
**Pull request by ymoslem**
If you are on a CPU-only machine, it will give an error otherwise. Model averaging should not require a GPU; moreover, it may be faster to use CPU rather than move all models to the GPU to average them.

### CODE REVIEW

**Comment by ymoslem** [comment]
Reference: https://github.com/OpenNMT/OpenNMT-py/issues/1374#issuecomment-499055146

**Comment by ymoslem** [comment]
@vince62s Hi Vincent! I do not know why the errors in the check; it works fine offline. Anyhow, the edit is connected to the comment above. It is up to your evaluation to merge it or not.

**Comment by vince62s** [comment]
We need to check the Travis thing, unrelated to your PR.

**Comment by guillaumekln** [comment]
Looks like to be related to the latest torchaudio commit https://github.com/pytorch/audio/commit/a420cced7e60fcf9ba6efcff3a2e8bee3ac67d05 which requires nightly versions of PyTorch. The dependency should be pinned to the previous commit.

**Pull request merged**
