### PR TITLE
Implements random sampling.

### PR DESCRIPTION
**Pull request by daphnei**

### CODE REVIEW

**Comment by vince62s** [comment]
Hi @daphnei, thanks for this.
there are a bunch of flake issues to fix, plus it seems it did not complete some translate steps in the build, can you try to fix these ?
Also is there a paper reference to add and some results ?
cheers.

**Comment by daphnei** [comment]
Sorry this was a mistake! I meant to send this to my friend's repo, not do a pull request to the main one. I am closing.

**Comment by vince62s** [comment]
this is too bad, why not contributing to the opensource project ?

**Comment by daphnei** [comment]
This is part of an effort by me and a colleague to implement and compare a bunch of different decoding strategies. Once I've cleaned up and tested the code more extensively, I'll submit a proper pull request.

**Pull request closed without merging**
