### PR TITLE
Bug fix of AudioSeqField

### PR DESCRIPTION
**Pull request by takatomo-k**
On Speech to text task.
In AudioSeqField class
You forgot to map "arr" to the device.

### CODE REVIEW

**Comment by vince62s** [comment]
@flauted was this introduced recently?

**Comment by flauted** [comment]
Thanks for the fix!

Probably introduced when the AudioSeqField was introduced.

I ran into something similar working on the video captioning stuff. I think ImageSeqField has a similar problem, and I don't think either will work with half-precision right now.

**Comment by vince62s** [comment]
shouldn't it be arr = arr.contiguous().to(device) ?

**Comment by takatomo-k** [comment]
Thank you for your comment.
->shouldn't it be arr = arr.contiguous().to(device) ?
Yes, I think so. 
Maybe "contiguous()" not necessarily because of below code. arr=arr.to(device) is enough.
#line 211
if self.sequential:
            arr = arr.contiguous()

**Comment by vince62s** [comment]
can you amend your PR please?

**Comment by vince62s** [comment]
please fix flake.

**Pull request merged**
