### PR TITLE
Update help string for `fix_word_vecs_*`

### PR DESCRIPTION
**Pull request by ygorg**
Hi, according to #1866 I changed the help string for the `fix_word_vecs_*` to be clearer about what it does.
I wonder whether it is necessary to change the variable names using this option as well ?
I think just changing the help is enough string will help user understand what this does.

The 3 files using this option:
- [onmt/model_builder.py](https://github.com/OpenNMT/OpenNMT-py/blob/2c63a535c8c85ba77eeac2e179cfa0e70d0a90fe/onmt/model_builder.py#L37)
- [onmt/modules/embeddings.py](https://github.com/OpenNMT/OpenNMT-py/blob/2c63a535c8c85ba77eeac2e179cfa0e70d0a90fe/onmt/modules/embeddings.py#L110)
- [onmt/tests/test_embeddings.py](https://github.com/OpenNMT/OpenNMT-py/blob/2c63a535c8c85ba77eeac2e179cfa0e70d0a90fe/onmt/tests/test_embeddings.py#L24)

This file explains what the option does more explicitly: [docs/source/FAQ.md](https://github.com/OpenNMT/OpenNMT-py/blob/master/docs/source/FAQ.md#example)

### CODE REVIEW

**Comment by francoishernandez** [comment]
Hi @ygorg 
Thanks for this. I think we can rename the variables as well. As you may have seen, we're preparing for a 2.0.0 release, and such changes can be part of it.
Also maybe add a note in the FAQ that you mention about these options.

**Comment by ygorg** [comment]
I changed variables name and option name as well (tell whether I should revert the option names).
Added a docstring in Embedding class.
In the FAQ there's already a note about freezing embedding, not sure what I can add :
`* additional flags fix_word_vecs_enc and fix_word_vecs_dec are available to freeze the embeddings.`

The tests using pretrained models fail because of the changed option name. I don't know what I should do about that.

**Comment by francoishernandez** [comment]
> In the FAQ there's already a note about freezing embedding, not sure what I can add.

Indeed, forgot about this.

> The tests using pretrained models fail because of the changed option name. I don't know what I should do about that.

We probably can adapt the `model_builder` code to ignore these flags when loading a model for inference, as it's not inference related. Not sure what would be the cleanest though. @Zenglinxiao any idea?

**Comment by Zenglinxiao** [comment]
> We probably can adapt the `model_builder` code to ignore these flags when loading a model for inference, as it's not inference related. Not sure what would be the cleanest though. @Zenglinxiao any idea?
> (The idea being that it would be nice keeping backcompatibility working for inference.)

I think we can set the missing attribute `freeze_*` with previous `fix_word_vecs_*` (if hasattr()) in the `ArgumentParser.update_model_opts`. This guarantee valid options at the beginning and gather all those legacy options in the `parse.py` file to keep other files clean.

**Comment by ygorg** [comment]
Thanks i'll check how to do that.

**Comment by ygorg** [comment]
`tools/extract_embeddings.py` uses opts as in `bin/*` but didn't validate nor update the opts.
Which resulted in not adding `freeze_word_vecs` opt when needed.

**Review by Zenglinxiao — APPROVED** [review]
LGTM

**Comment by francoishernandez** [comment]
Looks good, thanks!
Merging.

**Pull request merged**
