### PR TITLE
QoL improvements

### PR DESCRIPTION
**Pull request by falcondai**
- merge with github's default python .gitignore file for comprehensiveness 
- freeze pytorch and torch-text version
- move dependencies to `requirements.txt`
- minor change to Travis config accordingly

### CODE REVIEW

**Comment by jekbradbury** [comment]
I'll make sure to tag the current master of torchtext and release it to pypi in the next day or two so you can refer to a stable version and install with pip.

**Comment by falcondai** [comment]
@jekbradbury that would be very helpful! I will update the `requirements.txt` accordingly.

**Comment by jekbradbury** [comment]
The current master is v0.1.2 on PyPI now https://pypi.python.org/pypi/torchtext

**Comment by sebastianGehrmann** [comment]
Great, thanks @jekbradbury! I changed the requirements.txt to use the PyPI version.

**Pull request merged**
