### PR TITLE
OpenNMT-py v3.0

### PR DESCRIPTION
**Pull request by vince62s**
This is the new v3.0 of OpenNMT-py

Main points:

1. Removed Torchtext completely (fields and Vocab), use of pyonmttok.Vocab object. see: https://github.com/OpenNMT/Tokenizer/tree/master/bindings/python#vocabulary
2. Checkpoint's structure has changed slightly. Use tools/convertv2_v3.py to upgrade previous models.
3. Use DataLoader for parallel data loading
4. Translation_server: src_feat and target_prefix not yet re-implemented
5. Library examples to come.
6. This version should be about 5% faster than v2.3

### CODE REVIEW

**Comment by anderleich** [comment]
Hi @vince62s ,

I was quickly checking the changes you are making for v3.0 and I found translate_dynamic.py has been deleted. Which is the reason behind this decision?

PD: I'm not aware of a better place to ask this. Is there a general issue/pull request for v3.0 where we can discuss these matters? Thanks

**Comment by vince62s** [comment]
what about gitter here: https://gitter.im/OpenNMT/OpenNMT-py ?

**Comment by medicine-wave** [comment]
Has ```target_prefix ``` been re-implemented?

**Comment by vince62s** [comment]
don't multi-post your questions.

**Pull request merged**
