### PR TITLE
New apex amp API

### PR DESCRIPTION
**Pull request by francoishernandez**
This PR updates the current mixed precision codepath with the new apex amp API according to the [guidelines](https://nvidia.github.io/apex/amp.html#transition-guide-for-old-api-users).

Default is `opt_level` "O2" which seems to correspond to what we were doing before. This can be changed by passing the `-apex_opt_level` option.

### CODE REVIEW

**Comment by memray** [comment]
I ran into an error after updating this commit. I ran Transformers on V100 and I tried with 1,2,4 GPUs.

```
 textPayload:  "Traceback (most recent call last):
  File "/export/home/OpenNMT-summary/train.py", line 149, in run
    single_main(opt, device_id, batch_queue, semaphore)
  File "/export/home/OpenNMT-summary/onmt/train_single.py", line 145, in main
    valid_steps=opt.valid_steps)
  File "/export/home/OpenNMT-summary/onmt/trainer.py", line 243, in train
    report_stats)
  File "/export/home/OpenNMT-summary/onmt/trainer.py", line 348, in _gradient_accumulation
    report_stats.n_src_words += src_lengths.sum().item()
  File "/export/home/anaconda/envs/py37/lib/python3.7/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA error: misaligned address
```
With *CUDA_LAUNCH_BLOCKING=1*, it outputs:
```
"Traceback (most recent call last):
  File "train.py", line 207, in <module>
    main(opt)
  File "train.py", line 93, in main
    single_main(opt, 0)
  File "/export/home/OpenNMT-summary/onmt/train_single.py", line 145, in main
    valid_steps=opt.valid_steps)
  File "/export/home/OpenNMT-summary/onmt/trainer.py", line 243, in train
    report_stats)
  File "/export/home/OpenNMT-summary/onmt/trainer.py", line 427, in _gradient_accumulation
    self.optim.step()
  File "/export/home/OpenNMT-summary/onmt/utils/optimizers.py", line 340, in step
    self._optimizer.step()
  File "/export/home/anaconda/envs/py37/lib/python3.7/site-packages/apex/amp/_process_optimizer.py", line 291, in new_step
    self._master_params_to_model_params()
  File "/export/home/anaconda/envs/py37/lib/python3.7/site-packages/apex/amp/_process_optimizer.py", line 250, in _master_params_to_model_params
    1.0)
  File "/export/home/anaconda/envs/py37/lib/python3.7/site-packages/apex/multi_tensor_apply/multi_tensor_apply.py", line 30, in __call__
    *args)
RuntimeError: CUDA error: misaligned address (multi_tensor_apply at csrc/multi_tensor_apply.cuh:103)
```

**Comment by memray** [comment]
It works well if I use `apex_opt_level=O0` but fails with other options. It usually errors out after a few successful batches.

**Comment by pltrdy** [comment]
@memray could you open an issue for this (providing details and exact training command line)? We've been in similar situations, we need to investigate. Is this issue specific to that PR? (i.e. it works before it)


Thanks.

**Comment by memray** [comment]
@pltrdy I started an issue [here](https://github.com/OpenNMT/OpenNMT-py/issues/1475). I think it's due to this PR. The other recent updates are not very relevant.

**Pull request merged**
