### PR TITLE
Bahdanau Attention

### PR DESCRIPTION
**Pull request by sebastianGehrmann**
Added Bahdanau style of attention to v0.2

### CODE REVIEW

**Comment by srush** [comment]
- Make sure that everything style checks with `flake8`
- Let's make a single GlobalAttention class and have options for Bahdanau or Luoung Attention
- Keep this PR to changes to attention, other style changes can be in a different PR.

**Comment by sebastianGehrmann** [comment]
flake8 checks out now. I removed all commits other than Bahdanau stuff from PR and merged it into globalAttention file.

**Comment by srush** [comment]
Looks great! 

Two more minor requests. 
1) Can you add type size assertions to the inputs and outputs? Look at how it is done in MultiHeadedAttn using the aeq() function?

2) Let's use Luong and Bahdanau as names in the comments, but have the user specify "dotprod" (luoung) or "mlp" as the option names.

**Comment by sebastianGehrmann** [comment]
Okay, I added both.

**Pull request merged**
