### PR TITLE
Fix bug: error when training from checkpoint with fix_word_vecs

### PR DESCRIPTION
**Pull request by fuzhenxin**
In #950 , problem arises when training from checkpoint with fix_word_vecs. 
Reason: when loading checkpoint, the fix_word_vecs is ignored in https://github.com/OpenNMT/OpenNMT-py/blob/9c6e32a7e9b4c8a66af5c1b196bb0dc9886ef6ec/onmt/model_builder.py#L291 
So i move the fix_words_vec setting to embedding initialization.

Another way is to add specific check after load checkpoint:
```
    if model_opt.fix_word_vecs_enc:
        model.encoder.embeddings.word_lut.weight.requires_grad = False
    if model_opt.fix_word_vecs_dec:
        model.decoder.embeddings.word_lut.weight.requires_grad = False
```

### CODE REVIEW

**Comment by vince62s** [comment]
@pltrdy if you get a chance, thanks.

**Comment by 520jefferson** [comment]
@vince62s @fuzhenxin  @pltrdy 
when i use 
train_from transformer_step_100000.pt  
 -pre_word_vecs_enc data_label/enc.100000.pt 
 -pre_word_vecs_dec data_label/dec.100000.pt   
 -fix_word_vecs_enc 
 -fix_word_vecs_dec 

i can train normally, but when i get model  transformer_step_100100.pt, i compare the word vector between transformer_step_100000.pt and transformer_step_100100.pt,, i find it change.

i get the word vector as follows:
 dec_emb = opennmt_model['model']['decoder.embeddings.make_embedding.emb_luts.0.weight'].data
 enc_emb = opennmt_model['model']['encoder.embeddings.make_embedding.emb_luts.0.weight'].data

is there something wrong ?

**Comment by fuzhenxin** [comment]
The pre_word_vecs_enc will not work when  loading checkpoint as in https://github.com/OpenNMT/OpenNMT-py/blob/f09cc8cf049ed50360f0654d4fc26f223de70369/onmt/model_builder.py#L179 and https://github.com/OpenNMT/OpenNMT-py/blob/f09cc8cf049ed50360f0654d4fc26f223de70369/onmt/model_builder.py#L208

If you need to load new embedding when training from ***, i recommend you to make https://github.com/OpenNMT/OpenNMT-py/blob/f09cc8cf049ed50360f0654d4fc26f223de70369/onmt/model_builder.py#L208 out of the if function.

**Comment by 520jefferson** [comment]
@fuzhenxin thanks a lot, i have will try that.
i have another question, i train the model with old codes. but i update codes today. i use train_from parameter and use old model , then i start triaining, i get this:
  File "/OpenNMT-py-master/onmt/train_single.py", line 93, in main
    optim = Optimizer.from_opt(model, opt, checkpoint=checkpoint)
  File "/OpenNMT-py-master/onmt/utils/optimizers.py", line 277, in from_opt
    build_torch_optimizer(model, optim_opt),
  File "/OpenNMT-py-master/onmt/utils/optimizers.py", line 88, in build_torch_optimizer
    if opt.model_dtype == 'fp16':
AttributeError: 'Namespace' object has no attribute 'model_dtype'

it seems new codes can not work well with older models, i will let model_dtype related codes commented out.

**Comment by fuzhenxin** [comment]
2. Whether the vec is fixed is set in https://github.com/OpenNMT/OpenNMT-py/blob/f09cc8cf049ed50360f0654d4fc26f223de70369/onmt/modules/embeddings.py#L171
However the model_opt in https://github.com/OpenNMT/OpenNMT-py/blob/f09cc8cf049ed50360f0654d4fc26f223de70369/onmt/model_builder.py#L107
 is loaded from the checkpoint as in https://github.com/OpenNMT/OpenNMT-py/blob/f09cc8cf049ed50360f0654d4fc26f223de70369/onmt/train_single.py#L55 . So your new fix_vec does not work. I recommend you to set the word_lut.weight.requires_grad in a proper position.

**Comment by 520jefferson** [comment]
@fuzhenxin i still have another question, do new codes not work well with old model? i set fix_word_vecs = True before embedding,  and i start the training , i have met  this below:

  File "OpenNMT-py-master/train.py", line 109, in <module>
    main(opt)
  File "OpenNMT-py-master/train.py", line 39, in main
    single_main(opt, 0)
  File "OpenNMT-py-master/onmt/train_single.py", line 93, in main
    optim = Optimizer.from_opt(model, opt, checkpoint=checkpoint)
  File "OpenNMT-py-master/onmt/utils/optimizers.py", line 282, in from_opt
    optimizer.load_state_dict(optim_state_dict)
  File "OpenNMT-py-master/onmt/utils/optimizers.py", line 310, in load_state_dict
    self._optimizer.load_state_dict(state_dict['optimizer'])
  File "/.local/lib/python3.5/site-packages/torch/optim/optimizer.py", line 114, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

**Comment by 520jefferson** [comment]
@vince62s  @fuzhenxin 
state_dict can not work fine when i use train_from and fix_word_vecs , after i restart training , i met this erorr: 
 File "OpenNMT-py-master/onmt/utils/optimizers.py", line 282, in from_opt
    optimizer.load_state_dict(optim_state_dict)
  File "OpenNMT-py-master/onmt/utils/optimizers.py", line 310, in load_state_dict
    self._optimizer.load_state_dict(state_dict['optimizer'])
  File ".local/lib/python3.5/site-packages/torch/optim/optimizer.py", line 114, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

i checked the groups and saved_groups , the params of them are different, groups like this:
image
saved_groups like this:
image

**Comment by fuzhenxin** [comment]
The reason is that the optimizer contains the "params" which may relate to the "Momentum". After you fix the embedding, the embedding momentum in checkpoint can not be loaded. The params in state_dict  https://github.com/OpenNMT/OpenNMT-py/blob/f09cc8cf049ed50360f0654d4fc26f223de70369/onmt/utils/optimizers.py#L310
is longer than the params in self._optimizer.load_state_dict. So deleting the unnecessary params may work. Just like 
```
state_dict['optimizer']["param_groups"][0]["params"] = state_dict['optimizer']["param_groups"][0]["params"][1:]
```
The first two elements in params may correspond to the word embedding.
You can verify whether it works.

In addition strict is useful but it does not work in optimizer.
https://github.com/pytorch/pytorch/issues/3852

**Comment by 520jefferson** [comment]
@fuzhenxin  
Thanks for the quick reply.
If i use the config --reset_optim all, it can work fine. Is there something that will harm mine train?  I use the pretrain optimizer's params, or maybe i just initialize again.

**Comment by fuzhenxin** [comment]
The weight decay may influence your results. I don't know other influences.

**Pull request merged**
