### PR TITLE
Simplify encoder

### PR DESCRIPTION
**Pull request by bpopeters**
I decided to polish the sketch of how I envisioned the encoder from a few days ago. This is still in progress, but I think a treatment like this would have eased some debugging I was doing earlier today. Maybe the code needs more assertions than it has right now, but it seems to be running fine. In principle, it should be possible to do something similar with the decoder as well.

### CODE REVIEW

**Comment by bpopeters** [comment]
Another model-rebuilding problem.

**Comment by srush** [comment]
Haha, well the purpose of that test is to discourage people from breaking pretrained models. Do you feel that you have done all you can to make sure all models work?

**Comment by bpopeters** [comment]
I trained it for an epoch or two on datasets both with and without features.

**Comment by srush** [comment]
I guess what I am saying is that ideally we wouldn't  retrain test models unless you feel it is absolutely necessary to change the parameter layout. It requires that we retrain all the benchmarks.

Are you asking why it is breaking? You can see that by running looking at the Travis logs above or running test/pull_req_chk.sh

**Comment by bpopeters** [comment]
Oh, I get completely why it's breaking and I understand if you either want to disregard this or leave it for a future time when we need to break the modules for something more important. I just decided to share it because I'm using it for some stuff specific to my own research right now and it seems to be working okay.

**Comment by srush** [comment]
Okay! I'll do a longer read.

**Comment by srush** [comment]
I'm going to pass on this for now. If something else come up that requires a breaking change, I'll reconsider it.

**Comment by bpopeters** [comment]
Okay, that's fine. It's fallen behind all the other rapid changes from the last week. I've been working on other concerns of mine recently and so it'll be a little while before I can push for the sorts of improvements in readability and extensibility I'd like to see here and in the Decoder.

**Comment by srush** [comment]
Sounds good! work is highly appreciated. 

Actually, I was going to add you officially to the maintainers list. Is that okay?

**Comment by bpopeters** [comment]
Sure.

**Pull request closed without merging**
