### PR TITLE
Remap args

### PR DESCRIPTION
**Pull request by flauted**
1. The rnn size arguments are used for non-recurrent architectures. That should be fixed.

2. The CLI for the non-text architectures don't reflect the code well. The encoder_type and decoder_type args are basically useless. Only the model_type arg matters.

This is related to #1231 .

Here's the argument mappings I'm proposing:

``-*rnn_size`` -> ``-*size``

``-encoder_type brnn`` -> ``bidirectional``

``-input_feed 0`` -> ``-decoder_type rnn``

``-input_feed 1`` (default) -> ``-decoder_type ifrnn`` (default)

(These aren't replacements, more like duplications:)

``-model_type img`` => ``-encoder_type img``

``-model_type audio`` => ``-encoder_type audio``

Here's new vs old on what commands generate.

**Defaults**
```
NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(50004, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(50004, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500, bias=False)
      (linear_out): Linear(in_features=1000, out_features=500, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=500, out_features=50004, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
```
Old
```
python train.py -data data/demo -save_model demo-model -world_size 2 -gpu_ranks 0 1 -save_checkpoint_steps 500 -train_steps 1000
```
New
```
python train.py -data data/demo -save_model demo-model -world_size 2 -gpu_ranks 0 1 -save_checkpoint_steps 500 -train_steps 1000
```

**Bidirectional**
```
NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(50004, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 250, num_layers=2, dropout=0.3, bidirectional=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(50004, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(1000, 500)
        (1): LSTMCell(500, 500)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500, bias=False)
      (linear_out): Linear(in_features=1000, out_features=500, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=500, out_features=50004, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
```
Old
```
python train.py -data data/demo -save_model demo-model -world_size 2 -gpu_ranks 0 1 -save_checkpoint_steps 500 -train_steps 1000 -encoder_type brnn
```
New
```
python train.py -data data/demo -save_model demo-model -world_size 2 -gpu_ranks 0 1 -save_checkpoint_steps 500 -train_steps 1000 -bidirectional
```

**No input feed**
```
NMTModel(
  (encoder): RNNEncoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(50004, 500, padding_idx=1)
        )
      )
    )
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
  )
  (decoder): StdRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(50004, 500, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): LSTM(500, 500, num_layers=2, dropout=0.3)
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=500, out_features=500, bias=False)
      (linear_out): Linear(in_features=1000, out_features=500, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=500, out_features=50004, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
```
Old
```
python train.py -data data/demo -save_model demo-model -world_size 2 -gpu_ranks 0 1 -save_checkpoint_steps 500 -train_steps 1000 -input_feed 0
```
New
```
python train.py -data data/demo -save_model demo-model -world_size 2 -gpu_ranks 0 1 -save_checkpoint_steps 500 -train_steps 1000 -decoder_type rnn
```

**Image, bidirectional**
```
NMTModel(
  (encoder): ImageEncoder(
    (layer1): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (layer2): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (layer3): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (layer4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (layer5): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (layer6): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (batch_norm1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (batch_norm2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (batch_norm3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn): LSTM(512, 5, num_layers=2, dropout=0.3, bidirectional=True)
    (pos_lut): Embedding(1000, 512)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(57, 5, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(15, 10)
        (1): LSTMCell(10, 10)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=10, out_features=10, bias=False)
      (linear_out): Linear(in_features=20, out_features=10, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=10, out_features=57, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
```
Old
```
python train.py -model_type img -data /tmp/im2text/q -batch_size 10 -word_vec_size 5 -report_every 5 -rnn_size 10 -train_steps 10 -encoder_type brnn
```
New
```
python train.py -model_type img -data /tmp/im2text/q -batch_size 10 -word_vec_size 5 -report_every 5 -size 10 -train_steps 10 -encoder_type img -bidirectional
```

**Audio, bidirectional**
```
NMTModel(
  (encoder): AudioEncoder(
    (dropout): Dropout(p=0.3)
    (W): Linear(in_features=2, out_features=2, bias=False)
    (batchnorm_0): BatchNorm1d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (rnn_0): LSTM(161, 1, dropout=0.3, bidirectional=True)
    (pool_0): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (rnn_1): LSTM(2, 1, dropout=0.3, bidirectional=True)
    (pool_1): MaxPool1d(kernel_size=1, stride=1, padding=0, dilation=1, ceil_mode=False)
    (batchnorm_1): BatchNorm1d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (decoder): InputFeedRNNDecoder(
    (embeddings): Embeddings(
      (make_embedding): Sequential(
        (emb_luts): Elementwise(
          (0): Embedding(18, 5, padding_idx=1)
        )
      )
    )
    (dropout): Dropout(p=0.3)
    (rnn): StackedLSTM(
      (dropout): Dropout(p=0.3)
      (layers): ModuleList(
        (0): LSTMCell(7, 2)
        (1): LSTMCell(2, 2)
      )
    )
    (attn): GlobalAttention(
      (linear_in): Linear(in_features=2, out_features=2, bias=False)
      (linear_out): Linear(in_features=4, out_features=2, bias=False)
    )
  )
  (generator): Sequential(
    (0): Linear(in_features=2, out_features=18, bias=True)
    (1): Cast()
    (2): LogSoftmax()
  )
)
```
Old
```
python train.py -model_type audio -data /tmp/speech/q -rnn_size 2 -batch_size 10 -word_vec_size 5 -report_every 5 -train_steps 10 -encoder_type brnn
```
New
```
python train.py -model_type audio -data /tmp/speech/q -size 2 -batch_size 10 -word_vec_size 5 -report_every 5 -train_steps 10 -bidirectional -encoder_type audio
```

### CODE REVIEW

**Comment by vince62s** [comment]
@bpopeters @guillaumekln @da03 we need to find a consensus on this.
I am not a super fan of encoder_type img/audio because these are more data/model types.
In theory we could have a transformer for audio or img (which would be nice to have btw).

For other suggestions, I am open but again things like input_feed might be generic to other type of encoders.

**Comment by flauted** [comment]
Yes you're right. When I get around to adding video-to-text, I'll be leaving it open to all the text models so yes that generality is necessary.

I did it this way because there literally is an ``AudioEncoder`` and `ImageEncoder``. Nothing about this approach except for the validation precludes you from trying to use a Transformer for image (although it certainly wouldn't work right now).

Maybe we could call those two something more meaningful at the command line? I don't know.

**Comment by guillaumekln** [comment]
It's not easy to name these 2 encoders. One way could be to use names from the associated papers. Here are some ideas:

* The image encoder comes from [What You Get Is What You See](https://arxiv.org/pdf/1609.04938v1.pdf), also referenced as WYGIWYS. But `-encoder_type wygiwys` while accurate is not very clear...
* The audio encoder is apparently related to the [Deep Speech 2](https://arxiv.org/pdf/1512.02595v1.pdf) architecture. So `-encoder_type deepspeech2` could be a way to name it.

One the subject of renames, I prefer "self_attention" over "transformer" when considering the encoder independently, but both are meaningful.

Also, not sure about `-decoder_type ifrnn` mostly because input feeding is usually the default behavior of RNN decoders. IIRC the only reason it was a flag is because without it the decoder can be accelarated by cuDNN.

**Comment by vince62s** [comment]
to move on this:
`-*rnn_size` -> `-*size` =>OK
`-encoder_type brnn` -> `bidirectional` =>not now, let's keep it the same as the Lua version and 
also only the rnn is bidirectional so this makes it clear.

`-input_feed 0` -> `-decoder_type rnn`
`-input_feed 1` (default) -> `-decoder_type ifrnn` (default)
=> No, let's keep it as it is for now.

`-model_type img` => `-encoder_type wygiwys` => OK
`-model_type audio` => `-encoder_type deepspeech2` => OK

This does not break existing checkpoint, right ?

**Pull request closed without merging**
