### PR TITLE
Dynamic data loading for inference

### PR DESCRIPTION
**Pull request by anderleich**
This PR intends to add a dynamic data loading pipeline for inference to ensure consistency between training and inference. It allows the use of data transforms the same way it is applied during training. The key idea is to avoid preprocessing input data outside the OpenNMT-py framework before calling to the `translate.py` script.

A sample configuration file:
```
# Data
src: /path/data.src
tgt: /path/data.tgt  # Optional
src_feats: {"feat1": "/path/data.feat1", "feat2": "/path/data.feat2"}  # Optional

# Data processing
transforms: [onmt_tokenize] # InferFeats, etc.

### Transform options
#### onmt_tokenize
src_subword_type: bpe
tgt_subword_type: bpe
src_subword_model: /path/codes.txt
tgt_subword_model: /path/codes.txt
src_onmttok_kwargs: {"mode": "conservative", "joiner": "￭", "joiner_annotate": true, "case_markup": true}
tgt_onmttok_kwargs: {"mode": "conservative", "joiner": "￭", "joiner_annotate": true, "case_markup": true}

# Model info
model: models/BEST_MODEL.pt

# Inference
max_length: 300
gpu: 0
batch_size: 32

# Output
output: /path/output.txt
```

I've added two new classes to better handle and simplify the inference data loading, named `InferenceDataReader` and `InferenceDataIterator`. I've also done some cleanup to remove unused classes and functions.

This is the first commit which I expect to improve to handle all use cases. The Ctranslate2 interface in the server and the server itself should be still adapted to allow this dynamic data loading approach. Some new tests should be created and adapt the ones affected by this PR.

I would like to know if you find this PR useful before going any further.

Thanks

### CODE REVIEW

**Comment by francoishernandez** [comment]
Hey @anderleich 
That's interesting! The only challenge I see is that it would make inference a bit harder to setup. But at least it's consistent with training.
I don't have time to review right now, but you can probably start by fixing what's needed for the CI tests to pass :)

**Comment by francoishernandez** [comment]
Also, I think we need to retain support of the previous translation method. It might be used as a library component in some other places.

**Comment by anderleich** [comment]
Hi @francoishernandez 

> The only challenge I see is that it would make inference a bit harder to setup.

Translation with tokenized/preprocessed text can still be done. No transforms would be applied in this case.

> Also, I think we need to retain support of the previous translation method. It might be used as a library component in some other places.

What classes or methods should I keep to support the previous translation pipeline? All of them? I've restructured the code with new classes to simplify the process. Maybe I could just rename some of them...

**Comment by francoishernandez** [comment]
@anderleich maybe the easiest for now would be to create a `translate_dynamic` bin to include all your logic, without breaking the current one? (And prefixing the new methods in the same way in the various classes that require adaptation.)

**Comment by anderleich** [comment]
@francoishernandez I've kept previous translation pipeline and added the necessary scripts and functions to support the new dynamic data loading approach. I've tried to keep things simple to avoid adding innecessary complexity to the code.

Now CI tests are passing. I guess there will be minor issues that will need to be reviewed but the main functionality is already done.

**Pull request merged**
