### PR TITLE
A data loader with support for dynamicly sampled noise and task-mix scheduling

### PR DESCRIPTION
**Pull request by Waino**
This pull request is *not* intended to be merged directly (it is not even up to date with master).
The implementation is intended as a prototype and conversation starter, and hopefully to inform the design of a set of changes to the OpenNMT-py dataloader.

We contribute a replacement for the OpenNMT-py dataloader, with two new features: dynamicly sampled noise and task-mix scheduling.

A more detailed argumentation and description of the new approach can be found in the `README.md` of the fork. Here is a short summary of the arguments:

Dynamicly sampled noise is important for methods using noise for regularization, such as subword regularization (Kudo, 2018). Task-mix scheduling is important in multilingual settings when different language pairs have different amounts of data, but can also be useful when mixing other types of data, such as different domains (oversampling the in-domain data), natural vs synthetic (e.g. back-     translated) data, and auxiliary tasks (e.g. autoencoder). The current implementation is difficult to use for segmentation research, as each experiment requires a separate preprocessing, leading to large waste of disk space.

### CODE REVIEW

**Comment by vince62s** [comment]
Hi @Waino,
Can you please elaborate on this "The current implementation is difficult to use for segmentation research, as each experiment requires a separate preprocessing, leading to large waste of disk space."
We already have the possibility to use various datasets, with various weights and you don't need to reprocess data when it comes to just changing weights.

**Comment by francoishernandez** [comment]
Hey @Waino 
Disclaimer: just scanned through your README fairly quickly, nothing more yet.
Thanks for all these proposals. The need for on the fly tokenization / noising / regularization seems legit, but I'm not sure about how your multi-task mix comes into all this. For instance, how would current multi weighted dataset setups would be converted to this new framework, one task per dataset?

**Comment by Waino** [comment]
Yes, the situation has been much improved by the feature that allows to weight different datasets, as before this oversampling had to be done off-line, which was colossally wasteful. Before this change, I had some experiments where my redundant preprocessed data consumed over a terabyte.

However, the current implementation still requires multiple preprocessing runs when experimenting with different preprocessing schemes, e.g. subword segmentation. If the segmentation is applied as off-line preprocessing, in addition to the original unsegmented corpus, each variant needs to be stored as a (temporary) segmented version which is then preprocessed into `.pt` files. This can still quickly build up.

Also, the current implementation only allows a constant mixing weight. A varying schedule could be specified in many different ways, my proposal is just one. Doing it as command line arguments might become quite complicated, which is why I chose a data config.

**Comment by Waino** [comment]
@francoishernandez current multi weighted dataset setups would typically be converted to this new framework as one task per dataset. There is some flexibility: if several datasets share a weight (and also share all transforms), they can be combined into a single task.

A downside is that the common usecase of training on a single dataset would become more complicated. Training with a fixed task-mix schedule is somewhat compliated already (multiple command line arguments with lists of aligned values), so my system would replace brevity by readability at the cost of some boilerplate.

The data config is to some extent optional: it would be possible to extend the existing command line arguments instead, although I think that would become difficult to use.

**Comment by francoishernandez** [comment]
Also, how does this do performance-wise? The current dataloading scheme is quite optimized to max out GPU usage and reach interesting training speeds.
What kind of overhead(s) would be expected in your setup?

**Comment by Waino** [comment]
Performance is a downside in the current implementation. I moved the dataloader into a separate process even for single-GPU training in order to maintain maximal GPU usage. The current multiprocessing setup is suboptimal due to how our cluster is configured (exclusive_process). As a result, single-GPU training is noticeably slower.

I think these problems can be to some extent alleviated. Use of multiprocessing could be made optional when transforms are light. When using multiprocessing, the inter-process data transfer could be optimized by making the data loader send tensors to the GPU.

**Comment by francoishernandez** [comment]
> Performance is a downside in the current implementation. I moved the dataloader into a separate process even for single-GPU training in order to maintain maximal GPU usage. The current multiprocessing setup is suboptimal due to how our cluster is configured (exclusive_process). As a result, single-GPU training is noticeably slower.

current = your current branch or master ?

**Comment by Waino** [comment]
Sorry for the ambiguous expression. I was talking about my implementation. Edited to clarify.

**Comment by francoishernandez** [comment]
Ok, thanks.
Exclusive mode is indeed an issue in the current/master producer-consumer setup.

**Comment by francoishernandez** [comment]
This whole thing is very interesting, but, as you say in your intro, it's not mergeable as is and it might be a bit much for a single PR.
Would it be possible to start a gradual process to get some of these features in, without breaking the whole codebase at once?
E.g.
0. find a better way, if any, to handle exclusive mode (that would be nice to remove that from the equation to better grab the implications of other features regarding performance);
1. dynamic dataset with tokenization/sampling;
2. multi task.
(As said before, dit not look at the whole code yet so this might not be that easy, I understand.)

**Comment by Waino** [comment]
I agree: there should be a discussion about 1) which features are of interest and which can be immediately discarded and 2) for each feature, whether to aim for minimal changes to the current implementation, or design a replacement or parallel system. Minimizing unnecessary complexity is an important regard.

**Comment by francoishernandez** [comment]
Hey @Waino 
I'm closing this in favor of #1869 (where we solved the 'exclusive mode issue' by the way).
Thanks for kickstarting the work on this!

**Pull request closed without merging**
