### PR TITLE
Use six to handle renamed functions and modules between Py2/3

### PR DESCRIPTION
**Pull request by notnami**

### CODE REVIEW

**Comment by srush** [comment]
PR is failing with this error 

Loading model parameters.
Traceback (most recent call last):
  File "translate.py", line 128, in <module>
    main()
  File "translate.py", line 98, in main
    (sent_number, words), 'UTF-8'))
TypeError: str() takes at most 1 argument (2 given)

Do you know why?

**Comment by JianyuZhan** [comment]
It seems the `bytes()` compatibility problem in python 2/3.
This patch might fix the problem.

```
diff --git a/translate.py b/translate.py
index 80558a5..7dfec40 100755
--- a/translate.py
+++ b/translate.py
@@ -96,26 +96,27 @@ def main():
                 words = get_src_words(
                     src_sent, translator.fields["src"].vocab.itos)
 
-                os.write(1, bytes('\nSENT %d: %s\n' %
-                                  (sent_number, words), 'UTF-8'))
+                os.write(1, bytes(('\nSENT %d: %s\n' % (sent_number, words))
+                                  .encode('UTF-8')))
 
                 best_pred = n_best_preds[0]
                 best_score = pred_score[0]
-                os.write(1, bytes('PRED %d: %s\n' %
-                                  (sent_number, best_pred), 'UTF-8'))
+                os.write(1, bytes(('PRED %d: %s\n' % (sent_number, best_pred))
+                                  .encode('UTF-8')))
                 print("PRED SCORE: %.4f" % best_score)
 
                 if opt.tgt:
                     tgt_sent = ' '.join(gold_sent)
-                    os.write(1, bytes('GOLD %d: %s\n' %
-                             (sent_number, tgt_sent), 'UTF-8'))
+                    os.write(1, bytes(('GOLD %d: %s\n' %
+                                       (sent_number, tgt_sent))
+                                      .encode('UTF-8')))
                     print("GOLD SCORE: %.4f" % gold_score)
 
                 if len(n_best_preds) > 1:
                     print('\nBEST HYP:')
                     for score, sent in zip(pred_score, n_best_preds):
-                        os.write(1, bytes("[%.4f] %s\n" % (score, sent),
-                                 'UTF-8'))
+                        os.write(1, bytes(("[%.4f] %s\n" % (score, sent))
+                                          .encode('UTF-8')))
 
     report_score('PRED', pred_score_total, pred_words_total)
     if opt.tgt:

```

**Comment by JianyuZhan** [comment]
@notnami , would you please also fix the travis error?

**Comment by notnami** [comment]
I'll fix the errors and resubmit the PR.

**Pull request closed without merging**
