### PR TITLE
Split the Encoder class

### PR DESCRIPTION
**Pull request by JianyuZhan**
This PR aims at splitting the `Encoder` class to match its counterpart. This lays the ground for later series which would refactor the `forward()` interface.  I think we shall get a consensus on what the basic structure this class should be splitted into first.

As discussed with @bpopeters in https://github.com/OpenNMT/OpenNMT-py/pull/246, both versions resemble a lot, except some points, as in my comment it that thread. This PR also addresses srush's concern in https://github.com/OpenNMT/OpenNMT-py/pull/246.

**Patch list**
1. 33a3288 prep patch. Rename `TransformerEncoder` to `TransformerEncoderLayer`
2. e2446f1 **skeleton** patch. Add `make_encoder` function and related `*Encoder` classes
3. 1a8ff82 `ModelConstructor.py`:  create new file for model lifter. This addresses @srush's concern.

4. 89d7bf4 Factor out `MeanEncoder` 
5. 17a1290 Factor out `RNNEncoder`
6. 5cae001 Factor out `TransformerEncoder`
7. 8e627b3 Factor out `CNNEncoder`
8. fc9913e Replace the old `Encoder` class

### CODE REVIEW

**Comment by bpopeters** [comment]
Now that I've seen your implementation, I can certainly see the similarities, but only to a point. We have both defined separate modules for mean, RNN, etc. However, the functions of these modules is different. Here, these separate modules each define the entire encoding operation, starting with embedding lookup. In contrast, the submodules in my not-yet-complete attempt (the relevant bits are present in a comment in #246) do not implement the entire encoding process. They handle small parts of the process that can then be composed together in an easy-to-understand way (embedding lookup, followed by an encoder-specific forward pass) that is consistent across encoder types. This means that code such as embedding lookup only has to happen once overall. Contrast that from this PR, in which embedding lookup has to be done separately in each of `MeanEncoder`, `TransformerEncoder`, `ConvEncoder`, and `RNNEncoder`.

I like the ModelConstructor.py a lot as a way to clear up the clutter in Models.py.

**Comment by JianyuZhan** [comment]
Hi, @bpopeters,  I've looked at your implementation, I got your point. Yes, I admitted your `forward()` approach is easier to understand.  This PR is actually a verbatim split without much modification, I wanted to make sure it keep the same behaviors first. And I think your method is good, maybe this can be done together when later refactoring the `forward()` interface.

**Comment by srush** [comment]
Let's discuss this a bit more. While I agree there are differences in your two implementations, I think they both improve over the current status quo. The main question seems to be is whether there is a global Encoder class and a switch statement, or whether there is individual encoder class that share code through a base class of some sort. I am relatively agnostic which way we go, although would rather not have a switch statement in the middle of the code. 

As a final data point, there will be encoders in the future that don't use the same embedding based lookup. For instance, `ImageEncoder` and in the future `CharEncoder` and `SpeechEncoder`. In some ways it might be beneficial for these to not have to derive from a class that assumes we need an embedding lookup. 

Finally, now that we have a ModelController.py, do all those functions need to take all their arguments by name? Can't those functions take `opt` and pass them through? It seems clunky to me that to add a new option you need to change `train.py` and `ModelController.py`

**Comment by JianyuZhan** [comment]
> As a final data point, there will be encoders in the future that don't use the same embedding based lookup. For instance, ImageEncoder and in the future CharEncoder and SpeechEncoder. In some ways it might be beneficial for these to not have to derive from a class that assumes we need an embedding lookup.

Well, the base class `EncoderBase` doesn't assume the `embeddings` and only does embeddings lookup in each class should that class need it. See https://github.com/OpenNMT/OpenNMT-py/commit/ca6916855b04412b7ddd5ce80a45a89ff9fdd59c

> Can't those functions take opt and pass them through? It seems clunky to me that to add a new option you need to change train.py and ModelController.py

Makes sense. No need...

**Comment by srush** [comment]
Yes, I agree that EncoderBase works. But I think that @bpopeters sketch has
this issue.

**Comment by bpopeters** [comment]
> Yes, I agree that EncoderBase works. But I think that @bpopeters sketch has this issue.

It does indeed have this issue. But I still think generalizing over an important and conceptually related subset of possible encoders (in this case, text encoders) is a good idea.

> Finally, now that we have a ModelController.py, do all those functions need to take all their arguments by name? Can't those functions take opt and pass them through?

I've had thoughts related to this. For at least some of our modules, I think it would be straightforward to implement, say, a `classmethod` called `from_opt` that unpacks a Namespace (i.e. opt) and gives the relevant arguments to the constructor. Similarly, `from_dict` or potentially other things. Functions of this sort are pretty common in the scientific python universe.

**Comment by JianyuZhan** [comment]
> I've had thoughts related to this. For at least some of our modules, I think it would be straightforward to implement, say, a classmethod called from_opt that unpacks a Namespace (i.e. opt) and gives the relevant arguments to the constructor. Similarly, from_dict or potentially other things. Functions of this sort are pretty common in the scientific python universe.

Indeed, the `make_encoder()` and `make_decoder()` are just dispatcher, and just relay the `opt` and unpack it , then delegate to each concrete classes.

**v1 -> v2**

I've added two patches doing this:

9. fc1c8a5 make_encoder: pass an opt instead of all names.
   Now its interface is:  `make_encoder(opt, embeddings)`

10. fabb8b5 make_decoder: pass an opt instead of all names.
   Now its interface is: `make_decoder(opt, embeddings)`

**Comment by srush** [comment]
I am going to merge this because it is better and doesn't break anything, but @bpopeters feel free to consolidate more of the encoder information. 

- [ ] I think we should have a check_output as well to for the first return argument at least. 
- [ ] I am think that `lengths` should be required, non-NULL
- [ ] Not sure that the `hidden` argument is necessary, which classes use that? 
- [ ] the second return argument is a somewhat special case. think we might be able to get rid of that.

**Pull request merged**
