### PR TITLE
Extend ONMTDataset to enable a daum-based weight

### PR DESCRIPTION
**Pull request by jj-globant**
This is the first part of the plan described on #271 where `ONMTDataset` is extended so it can handle an extra field, `dw` (for datum-weight) that will enable to use a value that represents how authoritative a single datum is, to weight the calculation of the loss and affect less the ones which i want to use for the sake of completeness but that shouldn't be as important as the most authoritative ones.

The current module is within it's own `weights` "package", as to enable the community to inspect, improve, comment before trying to modify the core `IO`.

I'm planning to create the rest of the plan for the issue on the same "weights" directory to avoid clashes during development in case of the pull request being accepted

### CODE REVIEW

**Comment by srush** [comment]
So, I think I don't want to include "packages" like this. Particularly if they copy code. 

Can you send the PR as if it were a change to IO directly? It will help me see in the diff what the change is. 

Also for test, you shouldn't need to include the args directly. (I think). Most of the code should be now callable as functions.

**Comment by jj-globant** [comment]
@srush will do and include the other changes!

I'm not sure what you mean about not including the args... Do you mean the `sys.argv.extend` statements? I'm including those to make the test be just one call without command line args, and if i try to use modules that have the parser defined at the top level, i get errors. What do you suggest to do on those cases?

**Comment by jj-globant** [comment]
@srush let me know if this works better!

**Comment by jj-globant** [comment]
Closed PR as it is superseded by #290

**Pull request closed without merging**
