### PR TITLE
Add missing vocab_size and min_frec in building vocabulary

### PR DESCRIPTION
**Pull request by fuzhenxin**
The vocab_size(max_size) and min_freq in _build_field_vocab is missing in the current version.

### CODE REVIEW

**Comment by vince62s** [comment]
Did we forget this in a recent PR or this has been the case for a long time ?

**Comment by vince62s** [comment]
@bpopeters did we miss this in a recent PR ?

**Comment by bpopeters** [comment]
#1132 made it possible to shorten the code in `build_vocab` and I accidentally omitted the kwargs from the `_build_field_vocab` calls when I updated it.

Should maximum sizes and minimum frequencies also apply to features?

**Comment by vince62s** [comment]
No I don' think so, the most common use case of features for NMT is POS tagging, case feature, lems, ...would not be applicable.

**Pull request closed without merging**
