### PR TITLE
preprocess empty lines as empty

### PR DESCRIPTION
**Pull request by sebastianGehrmann**
Added a check whether a line is empty when reading in a corpus during preprocessing. 

#284 #252

### CODE REVIEW

**Comment by sebastianGehrmann** [comment]
No merging yet please. If only tgt or src has an empty line at a place, it will desync the loading. I'm trying to figure out a way around it.

**Comment by srush** [comment]
I don't think the behavior we want is to drop the line. I think we want it to remain blank and not fail.

**Comment by sebastianGehrmann** [comment]
That's what I did in the latest commit. Checking right now if it crashes the model code to have an empty input

**Comment by bpopeters** [comment]
I have only one concern about this. The Dataset currently figures out how many features there are by peeking at the first training example. In the event that the first training sample is blank, we'll need to find out about the features some other way.

**Comment by srush** [comment]
Does this work? Have you tried translating a file with blank lines?

**Pull request merged**
