### PR TITLE
Update CTranslate2 usage for 2.0

### PR DESCRIPTION
**Pull request by guillaumekln**
Conversion of OpenNMT-py models is now simpler. The options are checked inside the converter.

### CODE REVIEW

**Comment by francoishernandez** [comment]
Hey @guillaumekln 
Thanks for this.
Would you mind retaining the <2.0.0 compatible conversion code? I think some of the breaking changes in 2.0.0 may cause some issues in the REST server which was not refactored yet.

**Comment by guillaumekln** [comment]
Hello! Right, is it OK if I update the REST server as well? I think we just need to add `return_scores=True` to the translate method.

**Comment by francoishernandez** [comment]
Indeed, thought I had seen some things regarding batch_size etc. but I remembered wrong.
Thanks!

**Comment by guillaumekln** [comment]
Yes the batch_size changes are only on the C++ side.

**Pull request merged**
