### PR TITLE
Fix gpt2 architecture and inference

### PR DESCRIPTION
**Pull request by funboarder13920**
- fix transformer lm architecture to be in compliance with gpt2 original paper (removed one normalization layer, removed one residual addition)
- fix inference regarding step/cache usage (positional embedding when input is not a single word, keep mask if input is not a single word)
- factorize decoder.transformer.py
- rebuild model and fix tests

A difference remains in PositionwiseFeedForward: gpt2 in using GELU and we are using ReLU (option to chose the activation function added)
Also huggingface implementation has only one dropout in their corresponding PositionwiseFeedForward

### CODE REVIEW

**Comment by funboarder13920** [comment]
Tests fixed in #1972

**Review by francoishernandez — COMMENTED** [review]
Looks good. Shall we merge?

**Comment by vince62s** [comment]
is there a discussion about the use of Gelu vs Relu in the GPT2 paper ?

**Comment by funboarder13920** [comment]
There is no such discussion in GPT2 paper. The use of gelu is here https://github.com/openai/gpt-2/blob/a74da5d99abaaba920de8131d64da2862a8f213b/src/model.py#L25
Bert and following transformer papers use gelu

**Pull request merged**
