### PR TITLE
explicitly disable attention

### PR DESCRIPTION
**Pull request by juhuahuang**
I need to disable attention in my project for paraphrasing. I noticed that there are some other issues mentioned about disabling attention, so I made a fix and submit a PR. The disabled pieces of code run fine in my test, but I'm wondering if there is a test environment on your side to make sure that the code won't cause regression.

### CODE REVIEW

**Comment by juhuahuang** [comment]
In the change, if -global_attention is set to "disabled", then the self.attn in Decoder will be set to None, and decoder output will be set directly to rnn ouput puts by dec_outs = rnn_output; fake align vector will be created as a zero tensors and save to attns["std'].

**Comment by vince62s** [comment]
I don't really understand the need for the fake align vector, shouldn't it be simpler to bypass attention as discussed in #574 ?

**Comment by juhuahuang** [comment]
I originally did not create a fake align vector, but in the decoding process. attns["std"] will be retrieved and processed. If there is no fake align vector, it will through out exceptions. Creating a fake one may not seem elegant, but in decoding mode, decoder do not know if attention is enabled until it runs to the vector. to keep least change on the code, fake vector may be a good idea. Let me know your suggestion, I will try to find a best patch.

**Comment by oserikov** [comment]
So is there any hope to have this PR merged? The ability to disable the attention seems to be really important but nothing happens

**Comment by vince62s** [comment]
IMO this is a workaround, not a clean PR.
@guillaumekln @bpopeters if you fell I should merge this, let me know, but personally I would not, open to consensus.

**Comment by jennhu** [comment]
I also need to disable attention and would appreciate an official fix! #574 isn't a solution.

**Pull request closed without merging**
