### PR TITLE
Change behavior for feature dimensions

### PR DESCRIPTION
**Pull request by bpopeters**
This pull request changes the behavior of the `-feat_vec_size` and `-feat_vec_exponent` command line options for building embeddings. Previously, `-feat_vec_exponent` was only used for `-feat_merge concat` and `feat_vec_size` was only used for `-feat_merge mlp`. This would lead to a lot of frustration if a person had pretrained feature embeddings of a known dimension that they wanted to concatenate, because they couldn't just specify that dimension with `-feat_vec_size`.

I changed this so that if `-feat_vec_size` is specified, it is used. `-feat_vec_exponent` is only used to determine the feature embedding size if `-feat_vec_size` is not specified.

I also changed around a couple of variable names in Embeddings.py to be clearer (`word_vec_size` is a better description of the variable's purpose than `embedding_dim`) and more consistent with the names of the command line options (the corresponding flag is `-word_vec_size`). And finally, I moved the `nn.Module` super init farther down in the constructor because it's only necessary for the bit where submodules, parameters, and buffers are created, and that happens at the end.

### CODE REVIEW

**Comment by srush** [comment]
So we had been making an effort to make our argument names agree with the pytorch standards. For this reason we used embedding_dim instead of word_vec_size. But I think I agree with you that word_vec_size is clearer in this case.

**Comment by srush** [comment]
One question. Why do you but the super() init() call so low? Why not just start with that?

**Comment by bpopeters** [comment]
It can go anywhere before one starts registering submodules/parameters/buffers. I thought leaving it as late as possible acts as a separation between the non-module reasoning that needs to happen and the instantiation of the network stuff.

**Comment by srush** [comment]
Sounds good. @JianyuZhan see above. Let's add that to our style guide.

**Comment by JianyuZhan** [comment]
Yep, the `nn.Module`'s `__setattr__` will automatically capture the attributes and register them. I think this makes sense. Do we need to write them in the `pull_request_chk.sh` to capture this?

**Comment by srush** [comment]
Not sure I understand why this would change pull_request_chk.sh?

**Comment by JianyuZhan** [comment]
I mean adding some simple logic in `pull_request_chk.sh` to check the `early super __init__() call` and print a warning. Adding in the style guide would possibly be ignored.

**Pull request merged**
