### PR TITLE
Replace gcld3 with FastText

### PR DESCRIPTION
**Pull request by ArtanisTheOne**
gcld3 is slower and less accurate than fasttext according to these benchmarks [[accuracy](https://modelpredict.com/language-identification-survey#benchmark-results), [speed](https://modelpredict.com/language-identification-survey#runtime-speed--memory-consumption))

Also fixes the annoying gcld3 installation error fiasco due to protobuf as spoken about [in this issue](https://github.com/OpenNMT/OpenNMT-py/issues/2370)

### CODE REVIEW

**Comment by vince62s** [comment]
thanks for this. can you please fix the tests.

**Comment by ArtanisTheOne** [comment]
Done - the remaining warning complains about the length of the model URL

**Comment by vince62s** [comment]
thanks. did you test it in the clean transform? works fine?

**Comment by ArtanisTheOne** [comment]
Will test it now

**Comment by ArtanisTheOne** [comment]
Works fine

**Pull request merged**
