### PR TITLE
add copy attention gold scoring

### PR DESCRIPTION
**Pull request by Henry-E**
This appears to solve the issue people have been having with not being able to get gold score when using a model with copy attention. It follows the same logic as used in the beam search for generating copy attention probabilities. 

It also fixes a bug where the gold score was supposed to be reporting log probabilities but never applied `.log()` to the generated probabilities.

Some issues this might resolve
https://github.com/OpenNMT/OpenNMT-py/issues/756
https://github.com/OpenNMT/OpenNMT-py/issues/777
https://github.com/OpenNMT/OpenNMT-py/issues/425

### CODE REVIEW

**Comment by vince62s** [comment]
it may solve #749 too then.

**Comment by Henry-E** [comment]
I've noticed that OOV words in the gold target sentence are all converted to UNKs. Let me see if I can find a way to get them to use their indexes in the extended vocab instead.

**Comment by Henry-E** [comment]
sorry, i'm learning the hard way how pull requests work. This second commit isn't anything to do with the pull request. I didn't realise pushing a new commit to my master branch would cause this to update.

**Comment by Henry-E** [comment]
The out.log() thing actually only applies to the copy generator which returns regular probabilities. I'm just going leave a reference to this particular commit somewhere for anyone who wants to use the fix

**Comment by vince62s** [comment]
why don't you PR just this fix first ?
cheers.

**Comment by Henry-E** [comment]
Sure, it's easy to move `out.log()` into the if statement and then everything works as expected. But the perplexity it returns is still not quite right because of the UNK vs. OOV probabilities. I don't know practically how to fix that yet nor what the correct semantics ought to be. It's not something I need for the convai2 competition, which is what was motivating the fix for the copy attention gold score.

**Pull request closed without merging**
