### PR TITLE
Update setup.py to allow import

### PR DESCRIPTION
**Pull request by Shujian2015**

### CODE REVIEW

**Comment by pltrdy** [comment]
Not sure to understand what it is supposed to fix, could you provide a description?
Thx.

**Comment by Shujian2015** [comment]
SImilar problem like this: https://stackoverflow.com/questions/7583652/python-module-with-a-dash-or-hyphen-in-its-name/24659400. Have to change dash to import that package.

**Comment by pltrdy** [comment]
The module itself is `onmt`, so I still don't see the problem. 

Could you share the code that fails because of that?

**Comment by Shujian2015** [comment]
My bad... That works. Thanks.

**Pull request closed without merging**
