### PR TITLE
Fix `attn` shape annotation in `forward`

### PR DESCRIPTION
**Pull request by r3dir3ct**
`(batch x tlen, input_size)`->`(batch x tlen, slen)`

### CODE REVIEW

**Comment by francoishernandez** [comment]
Actually, it seems this is the only place in the code where `slen` is used. Everywhere else seems to be `input_size`. If you really want to homogenize, maybe switch `slen` to `input_size` in the code instead of the opposite in the comments.

**Comment by r3dir3ct** [comment]
> Actually, it seems this is the only place in the code where `slen` is used. Everywhere else seems to be `input_size`. If you really want to homogenize, maybe switch `slen` to `input_size` in the code instead of the opposite in the comments.
I think using `input_size` as source_length would be confusing since the `hidden_outputs` also use `input_size` to represent the number of neurons.

**Comment by francoishernandez** [comment]
This makes sense. CopyGenerator is quite a special case, and it might indeed be more explicit to use `slen` here. Please merge current master on your branch (just for CI checks to be happy), and I'll merge then.

**Comment by r3dir3ct** [comment]
> This makes sense. CopyGenerator is quite a special case, and it might indeed be more explicit to use `slen` here. Please merge current master on your branch (just for CI checks to be happy), and I'll merge then.

Alright, I have done it.

**Pull request merged**
