### PR TITLE
Added GPT2 as decoder layer and a utility function to load its weights

### PR DESCRIPTION
**Pull request by ashishu007**
GPT2 is different than TransformerDecoder in two ways:

1. GPT2 uses Conv1D for self-attn and feed-forward
2. GPT2 doesn't have any src-attn layer

But it can be used as a decoder by adding cross-attention (or src-attn) layer, as done in [huggingface's GPT2 implementation](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_gpt2.py#L302). 

Here, two main contributions are added:

1. I've changed the self-attention layer to Conv1D attention provided by [huggingface](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_gpt2.py#L123) so that GPT2's pre-trained weights can be loaded. For cross-attention (or src-attention), the same MultiHeadedAttn is used similar to TransformerDecoder class. I didn't change it to Conv1D mainly because I didn't want to mess with attention scores being calculated there, because attention scores calculated in the cross-attention layer are used for copy mechanism.
2. I've added a function to load pre-trained GPT2 weights to an NMTModel. The pre-trained weights are downloaded from huggingface only.

Please take a look and see if the code is correct, especially for the part where Conv1DAttention is used. I checked both, TransfomerDecoder (one with LinearLayer for attention calculation), and GPT2Decoder (one with Conv1D attention calculation) and the results are almost similar.

Thanks.

### CODE REVIEW

**Comment by ashishu007** [comment]
Sorry about the mess looks like I have done the experiments with the previous version. Will change the codes to the current version and then resubmit.

**Comment by francoishernandez** [comment]
Hi there,
Just to make sure I understand your goal correctly: do you want to use GPT-2 decoder (either pre-trained or not) in an encoder-decoder scheme?
If so, what does it bring? What are the results you're talking about? Are there some paper about such setups?

Anyways, it happens that @funboarder13920 is currently working on adding the proper data-loading, training and inference codepaths to support Transformer-based LMs (#1919).
So, adding GPT-2 specific modules, as well as a way to load pre-trained weights can fit right in.

**Comment by ashishu007** [comment]
Hi,

Yes, I want to use GPT2 in an encoder-decoder scheme. The main inspiration for this came from the following papers:

1. [Few-Shot NLG with Pre-Trained Language Model](https://www.aclweb.org/anthology/2020.acl-main.18.pdf)
2. [Leveraging Pre-trained Checkpoints for Sequence Generation Tasks](https://www.mitpressjournals.org/doi/full/10.1162/tacl_a_00313)

In [1], the authors demonstrate few-shot capability of using pre-trained LM for NLG. In [2], again various combinations of BERT, RoBERTa and GPT2 are used to achieve SOTA results on NLG tasks. 

Huggingface provides API for seq2seq models with pre-trained LMs, but I wanted to develop something similar in OpenNMT as it is much easier to customise, especially in terms of handling copy/coverage mechanisms. 

I guess, GPT2 specific module can be added in (#1919) only, by adding extra 'elif' statement like this:

`elif self_attn_type == "conv1d":
    self.self_attn = Conv1DAttention()
`

**Comment by francoishernandez** [comment]
@ashishu007 FYI we just merged #1919, if ever you would like to make a new submission.

**Pull request closed without merging**
