### PR TITLE
Relative Position Representations

### PR DESCRIPTION
**Pull request by francoishernandez**
#1198 
(This is heavily inspired by the tensor2tensor implementation.)
I did not test extensively but this seems to run properly.
Also, it does not seem to hinder performance much. I notice less than 5% slowdown on a single GTX 1080.

This is activated by setting the `-max_relative_positions` option. The default value in t2t is 20.

### CODE REVIEW

**Comment by vince62s** [comment]
it trains fine and log makes sense but at inference I am getting the following error:
```
Traceback (most recent call last):
  File "translate.py", line 42, in <module>
    main(opt)
  File "translate.py", line 27, in main
    attn_debug=opt.attn_debug
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/translate/translator.py", line 220, in translate
    batch, data, attn_debug, fast=self.fast
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/translate/translator.py", line 476, in translate_batch
    return_attention=attn_debug or self.replace_unk)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/translate/translator.py", line 641, in _fast_translate_batch
    batch_offset=batch_offset
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/translate/translator.py", line 520, in _decode_and_generate
    decoder_in, memory_bank, memory_lengths=memory_lengths, step=step
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/decoders/transformer.py", line 228, in forward
    step=step)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/decoders/transformer.py", line 78, in forward
    type="self")
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/modules/multi_headed_attn.py", line 207, in forward
    False))
  File "/home/moses/pytorchwork/OpenNMT-py/onmt/utils/misc.py", line 112, in relative_matmul
    x_tz_matmul = torch.matmul(x_t_r, z)
RuntimeError: invalid argument 6: wrong matrix size at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:492
```

**Comment by francoishernandez** [comment]
The issue seems to be with the cache mechanism, adding a dimension to the `key` too soon, hence breaking matmul.
Translate seems to work fine when disabling it. Not sure we have an opt to disable it though, I just forced the `layer_cache` to be `None` to test it.
I'll need to refactor `multi_headed_attn.py` a bit to handle this case as well.

**Comment by vince62s** [comment]
Works fine, thanks. Please cite the paper somewhere either in the readme frontpage or in the code (but unsure where to put it though)

**Comment by vince62s** [comment]
Great, merging.

**Comment by alphadl** [comment]
If the different values of ``-max_relative_positions`` ​​have a significant impact on the results? As you mentioned, t2t setted it as 20. @francoishernandez

**Comment by francoishernandez** [comment]
We did not tune much. The [original paper](https://arxiv.org/pdf/1803.02155.pdf) seems to state that the different values do not have much impact.

**Comment by guillaumekln** [comment]
Is it on purpose that the same embeddings are used for the keys and values? If I read it correctly, this does not match the paper and T2T implementation.

**Comment by francoishernandez** [comment]
Can't remember exactly, I think this did not make a significant difference. Do you have some additional experiments?

**Comment by guillaumekln** [comment]
I don't have additional experiments. I thought this was a mistake because the positions copy and the call to the embedding layer are unnecessarily duplicated:

https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/modules/multi_headed_attn.py#L174-L179

**Comment by francoishernandez** [comment]
Indeed, seems strange. We may run a few additional experiments separating K/V embeddings at some point to check. Otherwise we'll remove this duplicate call.

**Pull request merged**
