### PR TITLE
fix goldscore #1383

### LINKED ISSUE #1383: Gold score computation bug
The current gold score computation has an off-by-one error. The current code gathers the logps of tgt_in = tgt[:-1], but it should be tgt[1:]. This is because tgt[:-1] is the input to the LSTM (i.e. [START] + words, without an [END] token) and tgt[1:] is the output from the LSTM (i.e. no start, with an [END] token). 

Patch to fix is below 
```
diff --git a/onmt/translate/translator.py b/onmt/translate/translator.py
index dd23a82..a5ba1e9 100644
--- a/onmt/translate/translator.py
+++ b/onmt/translate/translator.py
@@ -803,7 +803,7 @@ class Translator(object):
             memory_lengths=src_lengths, src_map=src_map)
 
         log_probs[:, :, self._tgt_pad_idx] = 0
-        gold = tgt_in
+        gold = tgt[1:]
         gold_scores = log_probs.gather(2, gold)
         gold_scores = gold_scores.sum(dim=0).view(-1)
```

A related issue is that the current random sampling code has scores that do not correspond to logps for the sentence. An easy fix to this is the following, which just accumulates all the scores instead of taking the last one.
```
diff --git a/onmt/translate/random_sampling.py b/onmt/translate/random_sampling.py
index ddc073b..19b70aa 100644
--- a/onmt/translate/random_sampling.py
+++ b/onmt/translate/random_sampling.py
@@ -116,8 +116,12 @@ class RandomSampling(DecodeStrategy):
 
         self.ensure_min_length(log_probs)
         self.block_ngram_repeats(log_probs)
-        topk_ids, self.topk_scores = sample_with_temperature(
+        topk_ids, topk_scores = sample_with_temperature(
             log_probs, self.sampling_temp, self.keep_topk)
+        if self.topk_scores is not None:
+            self.topk_scores += topk_scores
+        else:
+            self.topk_scores = topk_scores
 
         self.is_finished = topk_ids.eq(self.eos)
 
@@ -145,6 +149,7 @@ class RandomSampling(DecodeStrategy):
             return
         is_alive = ~self.is_finished.view(-1)
         self.alive_seq = self.alive_seq[is_alive]
+        self.topk_scores = self.topk_scores[is_alive]
         if self.alive_attn is not None:
             self.alive_attn = self.alive_attn[:, is_alive]
         self.select_indices = is_alive.nonzero().view(-1)
```

### PR DESCRIPTION
**Pull request by vince62s**

### CODE REVIEW

**Comment by vince62s** [comment]
@flauted I just copied/pasted the code suggested by #1383 which seems correct to me, but incidently the test_random_sampling.py fails on this code.
Do you have any clue ? thanks.

**Comment by flauted** [comment]
Not sure but I'm thinking it has to do with how the RS scores were defined on #1284.

**Comment by flauted** [comment]
Yeah, in #1284 the random sampling scores were defined as the probability of the EOS token. The fix here changes that to be the lprob of the sentence. So the test cases in test_random_sampling will have to be changed to check equality of the sentence lprob instead of the EOS token. I would think that probably should be in a separate PR from fixing the off-by-one error.

**Comment by vince62s** [comment]
okay right, will do.

**Pull request merged**
