### PR TITLE
fixed the bug in issue #277

### PR DESCRIPTION
**Pull request by jingxil**

### CODE REVIEW

**Comment by srush** [comment]
@JianyuZhan can you look at this? Not sure we should need a different decoder for each RNN layer.

**Comment by jingxil** [comment]
@srush It can be done without adding any new class.  I just feel that it might be better to keep parent class `RNNDecoderBase` from being bothered by details of child class. Since a different decoder is not necessary, Let us go with the other approach.

**Comment by JianyuZhan** [comment]
@jingxil , I took a look at this issue, I figure we'd better modify the `SRU` code to fix this, not to add a new decoder, since `SRU` is more a RNN variant, not a new encoder/decoder type. And when pytorch support `SRU`, we will migrate to use it, so it would be also better not to disrupt the current encoder/decoder hierarchy.

**Comment by jingxil** [comment]
All right. I definitely need to take a deep look at the `SRU`. I tried SRU on a MT task.  It was truly much faster than other RNN variants. However, the accuracy started to drop drastically after reaching around 64%. This phenomenon repeated no matter how I set hyper parameters. While on the same dataset the LSTM can arrive at 79% steadily.

**Pull request closed without merging**
