### PR TITLE
Earlystopping

### PR DESCRIPTION
**Pull request by antoniovilarinholopes**
# Early Stopping

This pull request address one of the most common feature in all NMT frameworks: Early Stopping. In addition, Loss.py had two operations over a variable never used (log_likelihood variable); it also had a non-necessary if/else statement.

Two types of early stopping were added: after each epoch; after N batches (user-defined) are processed.

## Changes

- Trainer.py
- opt.py
- train.py
- Loss.py

#### Trainer.py

The Trainer class was updated: the train method is now designed for extension with an additional argument `**kwargs`; two additional methods were added, generate_checkpoint and drop_best_checkpoin -- the first is to avoid repeating code, while the second is to save the best model only.

Two additional classes are added to this module: EarlyStoppingTrainer and EarlyStopping. The first is just a subclass of the Trainer class, while the second is the concrete implementation of EarlyStopping as a callable class. Moreover, the EarlyStoppingTrainer is similar to the regular Trainer, but after accumulating the gradients it performs validation if the number of batches to perform validation was reached. 

Important note: as the number of validation points can be significantly high and the model can be quite big, a checkpoint is only saved if the model is improving. The last commit addresses this.

Finally, the new trainer only requires a callable function to refresh the validation iterator, making it compatible with the current train.py module.

#### opts.py

Three flags added: 

- earlystop_tolerance, the number of consecutive validation points without improvement
- earlystop_type, either "epoch" or "batch"
- earlystop_after_batches, only required for "batch" type, specifies the number of batches to perform validation
 
#### train.py

This module was updated accordingly with the additional features. Note there is full compatibility with the Trainer class and a typo was fixed in the tensor board logging ("valid" instead of "train").

### CODE REVIEW

**Comment by antoniovilarinholopes** [comment]
The CONTRIBUTING.md file is confusing: the guidelines are to run `tools/pull_request_chk.sh` but this script is in `test/pull_request_chk.sh`. The pull request was made initially without any flake8 verification. The last commit address all flake8 errors.

**Comment by srush** [comment]
This looks neat. Let me get all the other PRs checked in and then I will have a review.

**Comment by vince62s** [comment]
Hi @antoniovilarinholopes the code base has changed a lot since this. However early stopping is a nice feature that could go along with the choice / saving of optional metrics as discussed here #813 

Do you have time to work on this ? if not no problem, we'll find someone.
Thanks.

**Comment by antoniovilarinholopes** [comment]
Hi @vince62s, sorry for taking so long. I've a new version of early stopping on par with the latest commit. It's different than this version as a number of tasks are now delegated elsewhere (for instance, saving a model is done inside model_saver).  Therefore, it's a simplified version of this original pull request. 

I'll close this one and create a new pull request. Btw, I can't find `tools/pull_request_chk.sh` to validate whether everything is up to the standards.

**Comment by vince62s** [comment]
here: https://github.com/OpenNMT/OpenNMT-py/tree/master/onmt/tests

**Pull request closed without merging**
