### PR TITLE
Refactor IO.ONMTDataset

### PR DESCRIPTION
**Pull request by bpopeters**
The goal of this pull request is to simplify the process by which source and target files are read in and converted into ONMTDataset objects. The contributions can be divided into three parts:

1) I shortened `extractFeatures` so that the reader of code no longer needs to keep track of indexing logic, but merely a sequence of comprehensions with descriptive names. This also allows the assertion requiring all words to have the same number of features to be expressed in a clearer way. The `zip(*split_tokens)` trick is not always completely intuitive to the reader, but it is well-documented on the internet as a way to unzip a zipped sequence.

2) I rewrote the `ONMTDataset` constructor. Its previous iteration had two large loops, one for the source file and the other for the target file. I abstracted out the logic for reading and tokenizing a source/target file and put it in the `read_corpus_file` method. As well as separating file I/O from the distinct task of building the examples list for torchtext, this also makes the assertion that the source and target files be the same length much clearer. I also wrote a `construct_examples` method for creating the examples dictionaries for either the source or target sides separately. The source and target dictionaries can then easily be merged. This limits the duplication of similar/identical code for processing the source and target sides, and should make it easier to extend OpenNMT-py to allow target features. 

3) I made miscellaneous small changes to the code elsewhere, such as using the `torch.zeros().long()` constructor instead of making an empty `LongTensor` and filling it with zeros, as I believe that is slightly more efficient. I replaced `while True` loops with `count()` (although the fact that we have to do either of these things just to get the features dicts is a little frustrating).

This is just a first attempt; I think more refactoring should be possible.

### CODE REVIEW

**Comment by srush** [comment]
Looks great, and is definitely cleaner and more readable. 

Couple tests are failing, one is in python2.7 flake8

./onmt/IO.py:57:19: F402 import 'count' from line 7 shadowed by loop variable

and the other seems to be a Long that should be a Float.

If you fix them I will merge.

**Comment by srush** [comment]
Think this is the offending line 

`+            alignment = torch.zeros(src_size, len(data), src_vocab_size).long()`. That should be Float.

**Comment by bpopeters** [comment]
Oh woops, I found the bug but fixed it in the wrong way while you were writing that. Why is the src_map a FloatTensor down in that part of the code even though it's a LongTensor when it's created up in the examples?

**Comment by srush** [comment]
No good reason. Think the code that uses it expects a float. We could move the long->float conversion later down the line.

**Comment by bpopeters** [comment]
I think that `_` would be a good convention for private methods. My personal preference for naming would be lowercase_with_underscores because that's the style in most of the python I use, including pytorch.

**Comment by bpopeters** [comment]
That basically does it for the cleanup here, at least for now. The only other thing I've been trying out with it is doing the alignment with a sparse tensor. Using sparse vectors for the alignment seems like a good idea because the src_map tensors are typically more than 95% zero. The problem is that `torchtext.data.Field` can't account for that possibility unless you replace the tensor_type parameter with `lambda sparse: sparse.to_dense()`, which sort of defeats the purpose. However, it looks like maybe translation goes a little bit faster with the sparse alignment vector creation even so. Do you think it's a good idea, @srush ?

**Comment by srush** [comment]
Oh that's a fun idea. Let's look into it later. Think there will be uses for sparse vectors in opennmt, but I would like to understand their implementation a bit better first.

**Pull request merged**
