### PR TITLE
Language model

### PR DESCRIPTION
**Pull request by mattiadg**
Added language model. Added a script for training a language model and one script for computing the perplexity of a file with a trained model. 
I had to change preprocess.py in order to manage differently monolingual and
bilingual texts. 
I also had to change train.py for making it load only bilingual texts.

TO IMPLEMENT: generate sentences with the language model.

### CODE REVIEW

**Comment by srush** [comment]
This looks really neat. I would rather it not have a separate train file. See if you can integrate it into the current train script. This might involve abstracting some aspects out, but I think it will be better not to fork this file.

**Comment by mattiadg** [comment]
Ok, I'll work on it.

Il 01/Lug/2017 02:44 AM, "srush" <notifications@github.com> ha scritto:

**Comment by srush** [comment]
Sorry, I changed train.py a bit. Hopefully this makes things a bit simpler

**Comment by srush** [comment]
Would still love to have this. Let me know how thing are going, or if you want to help out with other projects.

**Comment by srush** [comment]
Sounds good! Just want to let you know that we are happy for any contributions.

**Pull request closed without merging**
