### PR TITLE
Add BPE and SentencePiece subword tokenization options

### PR DESCRIPTION
**Pull request by ymoslem**
During `build_vocab` the option `tokenization_type` can be set to either `bpe` or `spm`. If it is not set, i.e. `None`, the default is regular word-level vocabulary building.

### CODE REVIEW

**Comment by vince62s** [comment]
Thanks Yasmin.
I think I was not clear in what I think we need.
When you run build_vocab.py usually you do it with a config.yaml file in which there are options.

There are several cases:
case 1: you ALREADY have a bpe/spm model that is specified in your config.yaml file. In this case you don't want to build a new one, you just want to use it to tokenize your data and build a vocabulary.

case 2: you don't have it and you want to build a spm/bpe model, then use it to tokenize and build your vocab.

SO, I think the new option must be --learn_subword_type SPM/BPE
if this option is not set then do not learn, use the one in the config if there.
if it is set then learn a subword model, name it the name of the config (maybe we need to override it I think there is an overide option somewhere)

Let me know if this is clearer.

**Comment by ymoslem** [comment]
Hi Vincent!

Thanks for the clarifications!

I think I have applied case 2. I can apply case 1 and verify the conditions you mentioned.

Is not there a third case when the user just wants the default word-based tokenization? Does this happen when there is no model path in the config.yaml file?

Thanks!

**Comment by ymoslem** [comment]
Hi Vincent! Should we use `src_subword_type` as well? To define a tokenizer, `pyonmttok.Tokenizer` can take either `bpe_model_path` or `sp_model_path`. That is why there should be an option that set the subword type.

So, maybe we can use `src_subword_type` which currently takes `['none', 'sentencepiece', 'bpe']` while `learn_subword` can be simply a true/false argument?

**Comment by vince62s** [comment]
Either way. your solution with `learn_subword` as a Bool is fine to me as well.

**Comment by ymoslem** [comment]
This is an updated version. When `share_vocab` is false, should we do something different?

**Comment by vince62s** [comment]
ok, I need another clarification :)
The actual tokenization happens in the transform "tokenize" so you don't need to tokenize in this build_vocab.py
the only think you have to test is the flag and if true then run the learner.
if unclear, page me on gitter.im to direct message me.
https://app.gitter.im/#/room/#OpenNMT_OpenNMT-py:gitter.im

**Comment by ymoslem** [comment]
Thanks for the clarification! Should I remove tokenization altogether, or import the functions for the tokenize transform and run them?

**Comment by vince62s** [comment]
you need to remove it, it will happen automatically with this line https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/bin/build_vocab.py#L54
because in here, it calls the transforms.

**Comment by ymoslem** [comment]
Hi Vincent! Please let me know if we are getting closer. Probably, there are still some required edits; please let me know. Thanks!

**Comment by vince62s** [comment]
I realize my request is not clear at all and it will not work the way you started to do it, sorry for my lack of clear instructions.

Currently the work flow is as follow:

We suppose we already have a BPE model before calling build_vocab.py
We also suppose we use a config.yaml file with the settings of the bpe model above hence tokenize with it
We also have to take into account the n_sample setting which limit the number of ex (per dataset) used to build the vocab

To accomplish the build of the vocab, it call a method named build_vocab() which spawns multiple processes and call build_sub_vocab each working on a sub set of each dataset.

What do we want now ?
We would like to be able to build the BPE (or SPM) model and then to build the vocab using this bpe model.
In fact it has to happen in two steps, we can not build the bpe model in each sub process (can't work that way).
The other thing is that when building the bpe model we do not want tokenize using the transforms, we need to ingest plain text lines (cf the Tokenizer doc) and call the learner.

But it has to happen in two steps.
We need maybe a method build_subword_model()
this method loops over all datasets
the loop just ingest datasets at the file level using the learner.ingest_file("/data/train1.en") method (cf Tokenizer doc)
then it learns
then the build_vocab() method follows.

Would that work better ?

**Comment by ymoslem** [comment]
This makes sense.

I deleted this fork as some people starred it instead of the original repository. I will rethink about it locally at a later time. Meanwhile, if you think it will save you time to implement it without me, please do. Many thanks for your patience so far!

**Pull request closed without merging**
