### PR TITLE
Further IO refactoring

### PR DESCRIPTION
**Pull request by JianyuZhan**
This PR addresses #466.

Basically, after this further refactoring, the `IO.py` now just acts as a dispatcher and delegates work to specific `*Dataset`'s static methods.

Furthermore, I create a new `onmt/io/DatasetBase.py` to lodge `ONMTDatasetBase`, which could avoid the import circular dependency problem between `IO.py` and `*Dataset.py` ( Before this, `*Dataset` uses `IO.py`'s `ONMTDatasetBase`,  while `IO.py` uses `*Dataset.py`'s `*Dataset`, which will create a circular import problem).  And this separation seems good, it naturally de-entangles things and exposes more cleanup opportunities.

### CODE REVIEW

**Comment by srush** [comment]
Looks great! Nice change. 

Think we can even start adding some new ones, like a character dataset or a multi-text input.

**Comment by JianyuZhan** [comment]
@srush Great! I would like to implement some new research-oriented funny things later.

But for now, I think we still have some engineering problems to fix, I list them as below, please add your requirements if I miss anything.

1. The train side memory issue. The new torchtext version might have support for dataset generator that would facilitate solving this problem. I am looking at it. And hopefully we can upgrade our
torchtext version to fix some previous torchtext compatibility problems as well.

2. The pytorch new version compatibility problem

3. Attention refactoring.

**Comment by srush** [comment]
I agree with this order. Let me know if I can help with 1 or 2. Not sure if torchtext will fix this problem, I think we may need to fake an iterator that loads one shard at a time. 

3 is a bit trickier. Basically I think the decoder should take an attention module as an argument.

**Comment by JianyuZhan** [comment]
Okay.  I will try out the latest torchtext to see if it helps, otherwise I will fake the iterator on our side.

For 3, I will discuss with later when I am on it.

**Pull request merged**
