### PR TITLE
Experimental FP16 training

### PR DESCRIPTION
**Pull request by guillaumekln**
It uses the optimizer wrapper from https://github.com/NVIDIA/apex/ and simply defaults to an automatic loss scaling.

State of this branch: *it runs*, meaning the training runs in FP16 without producing NaN values (currently focusing on standard Transformer training). 

However, the gains appeared to be very small on a V100 (like 5% faster), that's why I'm opening this branch for testing and help.

Thanks.

### CODE REVIEW

**Comment by erip** [comment]
Solves #1099, FWIW. :)

**Comment by francoishernandez** [comment]
Hey @guillaumekln 
We're testing this on a RTX 2080Ti.

Before going into speed considerations we've got some GPU memory issues.
It seems `fp16` requires more memory than `fp32` mode for the exact same parameters.
E.g. `fp32` mode runs with batch size 3584 without any issue.
(6 layers, hidden size 512, vocab size 35k)
`fp16` mode fails with this strange
`RuntimeError: CUDA out of memory. Tried to allocate 112.38 MiB (GPU 0; 10.73 GiB total capacity; 4.75 GiB already allocated; 68.69 MiB free; 1.27 GiB cached)`

Also, in `fp16` mode, what do these logs refer to?
`OVERFLOW! Skipping step. Attempted loss scale: 67108864.0, reducing to 33554432.0`

Thanks!

**Comment by guillaumekln** [comment]
Hi, thanks for testing!

> It seems fp16 requires more memory than fp32 mode for the exact same parameters.

That's possible, as there is a full copy of the model parameters in FP32. However, because the model is executed in FP16, internal buffers require less memory. So after a certain batch size, the training should actually require less memory. There are certainly ways to make things better though.

In my case I tested using the `pytorch/pytorch:1.0-cuda10.0-cudnn7-runtime` Docker image and the following command line:

`python train.py -data data/wmt-ende -layers 6 -rnn_size 512 -word_vec_size 512 -max_grad_norm 0 -encoder_type transformer -decoder_type transformer -position_encoding -dropout 0.1 -param_init 0 -warmup_steps 4000 -learning_rate 2 -decay_method noam -adam_beta2 0.998 -batch_size 4096 -batch_type tokens -normalization tokens -world_size 1 -gpu_ranks 0 -max_generator_batches 0 -save_model models/test_model -accum_count 8 -seed 42 -optim adam -label_smoothing 0.1 -model_dtype fp16
`

Here are my results:

| | Memory usage (MB) | Speed (target token/s) |
| --- | --- | --- |
| FP32 | 14723 | 22.2k |
| FP16 | 13653 | 29.0k | 

Can you share more details about your configuration? Did you try with multiple GPUs also?

> Also, in fp16 mode, what do these logs refer to?

The loss is dynamically scaled to mitigate the reduced precision of FP16. However, this scaling can generate overflows in the computed gradients. When this happen, the loss scaling constant is reduced and the step is skipped.

**Comment by vince62s** [comment]
I think I saw something in the fairseq implementation to avoid to keep a fp32 copy all the time.

**Comment by francoishernandez** [comment]
Hey @guillaumekln,
here are some more thorough results.

Configuration:
- ubuntu 18.04.1 - Nvidia RTX 2080 Ti FE (x2) - driver 410.48
- python 3.6.7
- pytorch 1.0.0 / cuda 10.0 / cudnn 7401

Basis command:
`python3 train.py -data exp/dataset.en-de  -save_model exp/model.en-de  -keep_checkpoint 10  -encoder_type transformer -decoder_type transformer  -layers 6 -rnn_size 512 -word_vec_size 512  -heads 8 -transformer_ff 2048  -batch_type tokens -batch_size 2560 -accum_count 1 -gpu_ranks 0 -world_size 1 -max_generator_batches 4  -train_steps 5000 -valid_steps 1000 -warmup_steps 6000 -learning_rate 2  -max_grad_norm 0 -optim adam -decay_method noam -adam_beta2 0.998  -normalization tokens -dropout 0.1 -label_smoothing 0.1  -position_encoding -param_init 0  -param_init_glorot  -save_checkpoint_steps 1000 -seed 3435 -report_every 100  -model_dtype 'fp32'`

1. Single GPU

Batch size: 3072 // Accum 1

|  | Memory usage (MB) | Speed (target token/s) |
| --- | ------------- | ------------- |
| FP32 | 10549  | 14608  |
| FP16 | 9621  | 16774  |


Batch size: 3072 // Accum 2

|  | Memory usage (MB) | Speed (target token/s) |
| --- | ------------- | ------------- |
| FP32 | 9827  | 15247  |
| FP16 | 10207  | 19128  |

Batch size: 3072 // Accum 4

|  | Memory usage (MB) | Speed (target token/s) |
| --- | ------------- | ------------- |
| FP32 | 9917  | 14985  |
| FP16 | 9817  | 19575  |

2. Dual GPU

For whatever reason batch size 3072 does not fit when running FP16 on 2 GPUs while FP32 seems to run properly. Yet, reducing to batch size 2560, FP16 seems to use less memory than FP32.

Batch size: 2560 // Accum 1

|  | Memory usage (MB) | Speed (target token/s) |
| --- | ------------- | ------------- |
| FP32 | 9375 // 10533  | 15424  |
| FP16 | 9185 // 8645  | 21160  |

Batch size: 2560 // Accum 2

|  | Memory usage (MB) | Speed (target token/s) |
| --- | ------------- | ------------- |
| FP32 | 9267 // 10459  | 20092  |
| FP16 | 9305 // 9975  | 26593  |

Batch size: 2560 // Accum 4

|  | Memory usage (MB) | Speed (target token/s) |
| --- | ------------- | ------------- |
| FP32 | 10169 // 10805  | 23116  |
| FP16 | 10661 // 9863  | 31057  |

**Comment by vince62s** [comment]
@guillaumekln  can we do this ? https://github.com/pytorch/fairseq/pull/404

**Comment by francoishernandez** [comment]
FYI, here are the same 2-gpu experiments but setting `-max_generator_batches 0`.

Batch size: 2560 // Accum 1

| | Memory usage (MB) | Speed (target token/s) |
| --- | ---------------------- | ---------------------------- |
| FP32 | 9607 // 8501 | 16261 |
| FP16 | 6887 // 10681 | 22245 |

Batch size: 2560 // Accum 2

| | Memory usage (MB) | Speed (target token/s) |
| --- | ---------------------- | ---------------------------- |
| FP32 | 7703 // 9196 | 20916 |
| FP16 | 6845 // 10681 | 29497 |

Batch size: 2560 // Accum 4

| | Memory usage (MB) | Speed (target token/s) |
| --- | ---------------------- | ---------------------------- |
| FP32 | 7607 // 9185 | 25130 |
| FP16 | 6869 // 10689 | 34227 |

Additional test :
Batch size: 2560 // Accum 8

| | Memory usage (MB) | Speed (target token/s) |
| --- | ---------------------- | ---------------------------- |
| FP32 | 7637 // 9559 | 26580 |
| FP16 | 7239 // 10689 | 38597 |

**Comment by vince62s** [comment]
@guillaumekln I know this is ridiculous but we need a dummy commit to pass travis because it kept in cache a version of pep8-naming that requires some lowercase in names......

**Comment by francoishernandez** [comment]
Here are some more results on our side.

Basis command:
`python3 train.py -data exp/dataset.en-de  -save_model exp/model.en-de  -keep_checkpoint 10  -encoder_type transformer -decoder_type transformer  -layers 6 -rnn_size 512 -word_vec_size 512  -heads 8 -transformer_ff 2048  -batch_type tokens -batch_size 3584 -accum_count 8  -gpu_ranks 0 -world_size 1 -max_generator_batches 4  -train_steps 5000 -valid_steps 1000 -warmup_steps 6000 -learning_rate 2  -max_grad_norm 0 -optim fusedadam -decay_method noam -adam_beta2 0.998  -normalization tokens -dropout 0.1 -label_smoothing 0.1  -position_encoding -param_init 0  -param_init_glorot  -save_checkpoint_steps 1000 -seed 3435 -report_every 100  -model_dtype fp16`

**Please note that these results are using the `FusedAdam` Optimizer from apex.**

Speed in target tokens/s:

| accum_count | 1 | 4 | 8 |
| ---------------- | -- | -- | -- |
| 1 RTX 2080 Ti | 31.5k | 32.5k | 31.7k |
| 2 RTX 2080 Ti | 38.5k | 53.5k | 57.0k |

It's interesting to notice that accum does not bring much benefit in the case of a single RTX.

**Comment by vince62s** [comment]
Just for the record (and my own reminder), this PR uses the fp16_utils.FP16_Optimizer
we also tried the optimizers.FP16_Optimizer which is a cutdown version of the above and works very fast with FusedAdam. One caveat is that for some reason https://github.com/NVIDIA/apex/pull/123 is not merged at the moment.

**Comment by vince62s** [comment]
great thanks.

**Comment by vince62s** [comment]
@guillaumekln  we need to force fp32 at inference, or at least give the option to.
When translating on GTX1080ti a FP16 model is crazy slow.

**Comment by guillaumekln** [comment]
Maybe this can be done in the release_model script?

**Comment by vince62s** [comment]
Not very convenient.
Is there a real benefit to maintain an FP16 model inFP16 at inference time ? speed gain when running it on FP16 capable hardware ?

**Comment by guillaumekln** [comment]
Speed gains but also lower memory usage. There is no reason not to allow FP16 during translation.

**Comment by vince62s** [comment]
Same speed, same memory footprint by commenting out model.half()
If you have different results, let me know.
I suggest to add an option to force fp32 at inference even though I would prefer to set -fp16 also at inference.

**Comment by gvskalyan** [comment]
@vince62s  Can fp16 model be used on CPU during inference with --fp16 flag enabled

**Comment by vince62s** [comment]
no.
but on top of this, we made it the other way, you have to specify -fp32 to infer a fp16 model.

**Comment by gvskalyan** [comment]
May I know does the inference time differ from using a fp32 model and a fp16 model (with fp 32 flag) on an Intel CPU

**Comment by vince62s** [comment]
to me same speed.

**Comment by memray** [comment]
I tested the fp16 Transformer with copy attention. Two problems occur: (1) src_map needs to be cast to float16  before being fed to model; (2) keep inducing error "Gradient overflow.  Skipping step, reducing loss scale to xxx" until underflow. It seems that the CopyGeneratorLoss triggers something in apex mistakenly. 

Do you have any insight into this?

**Comment by AbelCui** [comment]
> I tested the fp16 Transformer with copy attention. Two problems occur: (1) src_map needs to be cast to float16 before being fed to model; (2) keep inducing error "Gradient overflow. Skipping step, reducing loss scale to xxx" until underflow. It seems that the CopyGeneratorLoss triggers something in apex mistakenly.
> 
> Do you have any insight into this?

I'm facing the same problem now. Did you have find any method to slove it?

**Comment by memray** [comment]
> > I tested the fp16 Transformer with copy attention. Two problems occur: (1) src_map needs to be cast to float16 before being fed to model; (2) keep inducing error "Gradient overflow. Skipping step, reducing loss scale to xxx" until underflow. It seems that the CopyGeneratorLoss triggers something in apex mistakenly.
> > Do you have any insight into this?
> 
> I'm facing the same problem now. Did you have find any method to slove it?

Nope, I gave up on fp16+copy.

**Pull request merged**
