### PR TITLE
Shuffle option in preprocess.py

### PR DESCRIPTION
**Pull request by JoostvDoorn**
Adds an in-memory solution for #1006.

### CODE REVIEW

**Comment by guillaumekln** [comment]
I'm not sure we want to load all data at once and break the sharding promise. Instead, we could shuffle within each shard, then randomly permute the shard order. @vince62s A comment here?

**Comment by vince62s** [comment]
I agree, we need to find a way without loading everything in memory.
I don't like much the alternate method because if let say, you concat Europarl + CommonCrawl then shard in 1M segements, you will keep shuffling data without mixing the 2 datasets.
Maybe we can random read the file at sharding time ?

**Comment by alphadl** [comment]
Yeah~ The situation @vince62s considered is very common especially handling the large scale multiple data files e.g., WMT. But I do not think your proposed random reading strategy at sharding time is wisdom because if doing so, it will be difficult to control and observe the training epochs. Maybe we can add an external bash script to shuffling the large scale corpus?

**Comment by JoostvDoorn** [comment]
@alphadl It should be possible to shuffle while sharding. You probably don't want to randomly read the file, but read line by line and randomly allocate each line to a shard and write multiple shard files at the same time. At the end you could shuffle each shard file separately.

**Pull request closed without merging**
