### PR TITLE
Datatype classes

### PR DESCRIPTION
**Pull request by flauted**
What: Abstracted data type differences to a datatype class and datatype objects as much as possible. 

Why: I want to add video captioning, but I don't want to make the data type handling messier by doing so.

How: Before, there was a dataset for each data type. They only implemented class and static methods. Now there is one dataset and a datareader (somewhat inspired by AllenNLP) for each type. A reader is instantiated once (verifying optional imports and storing any reading options) and pointed to a new file each use (so it doesn't need instantiated for each split, for each shard).

The bulk of the burden of adding a new data type is in defining the fields. Instead of having lots of datatype logic in ``inputter.py``, I've moved it to the datatype file. Each data type has a ``fields`` attribute that takes the side name and arbitrary arguments. If your new datatype needs additional arguments when making the fields, you simply add those arguments to the dictionary in ``inputter.py`` and your function will pull them out of the kwargs.

This is somewhat at odds with some of the changes in #1184. Namely, you can't check what instance your dataset is. To me, this makes sense. Someday, someone may add other output data types (text to speech for example). Since the dataset is actually a pair of two "datas" that can be different types, the dataset should be responsible for knowing each of those types. So, ``isinstance``ing is probably not the best anyways.

I've tested the ``pull_request_chk.sh`` against Python 2.7.12, 2.7.15, 3.6.8, and 3.7.2. @vince62s would you please take a look?

### CODE REVIEW

**Comment by vince62s** [comment]
Thanks a lot for this. I hope @bpopeters will also have time to review this.
However one first comment is that the way you did this refactor does not make it easy to read the changes because you created a new folder and some files that were moved and not necessarily changed a lot are completely off in the github view. Also for tracking purpose it's not the most convenient.
Do you find it really necessary to move these datatype readers in a specific folder ? (vs inputter)

What is exactly the use case "video captioning" you intend to accomplish ? (what is the src what is the tgt) I am quite interested.
Now, if your PR is supposed to support tgt dtypes that are other than text, we may need to include a minimal test set with Travis too.

**Comment by flauted** [comment]
By video captioning I roughly mean preprocessing=running a sequence of images through a CNN to extract a sequence of features (2D feat vecs and/or 3D feat vecs - [here](http://proceedings.mlr.press/v95/chen18b/chen18b.pdf)'s a paper that uses both, but a first pass would be just one or the other). So src is a sequence of (T x CNN DIM) feature vectors. In most cases, anyways. I'd also like to support feature maps from the CNN like [this](https://arxiv.org/pdf/1611.07837.pdf) paper. In all cases, target is text.

This PR does not support tgt dtypes but I designed so that someday if they are added, it won't be too much burden, i.e. reduce **some** of the assumption in the code that tgt is text dtype. So there's nothing to test there.

You're right on the diff. From an API sense it makes a lot of sense to have datatypes in one place and dataset in another (to me anyways). But from a diff sense it is a nightmare. I've essentially left the API as-is while moving the Readers back into the dataset files. The diff is a little better. I view that as a temporary fix. If this PR is accepted then we can do another that only moves the datareaders into the datatype files.

**Comment by flauted** [comment]
Actually it would basically be a feature vector datatype. If you view BERT as a preprocessing step then having a feature vector datatype could maybe let you use BERT embeddings for text-input problems like translation, at least on the input side of things. I hadn't thought of that before - not sure it's truly so easy, but definitely an interesting thought.

**Comment by vince62s** [comment]
the last commit does not really help. Maybe we can do this in 2 steps so that we can review the PR and keep history maintaining classes/functions face to face, and in later PR rename/reclass in a more meaningful way.

**Comment by flauted** [comment]
Sure.

**Pull request closed without merging**
