### PR TITLE
Refactor dataset

### PR DESCRIPTION
**Pull request by bpopeters**
This pull request makes some changes to IO.py in order to make the Dataset creation process clearer and easier to extend. Changes are primarily these:

1. I removed almost all of `ONMTDataset`'s static methods. They now live in IO.py as normal functions. Static methods are not necessary very often, and I felt that here they were obscuring the purpose of the `ONMTDataset` class here.
2. I altered the constructor of the `ONMTDataset` so that it no longer takes `opt` as an argument. Although this results in having to pass in more arguments, I think it is better to be explicit.
3. I consolidated the functionality of the various iterators over the data files. The process is now taken care of in the `read_corpus_file` generator.
4. I included an assertion in `ONMTDataset` that the `src_img_dir` is none, which seems reasonable since image datasets are not implemented yet.
5. I renamed the attribute that refers to the number of features to indicate that it is for source features. There is now also an attribute for the target features.

I noted in a comment on #283 that our work in not reading the whole source file in at once may not have the intended effect because the parent class's constructor often turns the examples sequence into a list, thus eliminating the benefit of doing things lazily. The parent class also implements `__getitem__`. Based on my inspection of the parent class, we don't really need to call its constructor, and I don't think we actually use the `ONMTDataset's` `__getitem__` anywhere, so we could just raise an error if it's called. More serious than that, though, is our use of `OrderedIterator`. We can't order the training data unless we're willing to store all of it at once.

### CODE REVIEW

**Comment by vince62s** [comment]
would it be possible to load a table of index in memory, index would be the numbered lines and we could store the number of tokens in the sentence, so that we could reorder as we need, but not load the full dataset in memory. Not sure if this feasible easily.

**Comment by bpopeters** [comment]
As per @srush's point in the #283 comment, the fact that the examples are loaded into a list isn't really a problem. The last paragraph of my post can be ignored.

**Comment by srush** [comment]
Hmm. So why not go one step further and just eliminate ONMTDataset as a class? We could just use Dataset now that all the methods have been removed?

**Comment by srush** [comment]
So, I think my main concern with the style of this PR is that it is not clear which methods should be called by outside functions and which are helpers. Can you use function names and comments, as well as placement in the file to make this clear? Ideally a user could look at the file and know which files they should call and are part of the API and which are just helpers. As it is there is no distinction.

**Comment by srush** [comment]
Just wanted to check in on this. Think I can merge, but should I wait for more changes?

**Comment by bpopeters** [comment]
There's still that bit with the ugly `__dict__` code for feature stuff. I've been rather busy with other things recently, but I might be able to have a look at that tomorrow.

**Comment by bpopeters** [comment]
I haven't gotten to the `__dict__` bits yet, but the first of today's commits allows us to sidestep a bug in torchtext. The `vocab.Vocab` constructor in torchtext creates `stoi` and `itos` attributes that are not the same length: `itos` contains two duplicate copies of the special symbols, which then don't end up in `stoi` because it's a dictionary and dictionaries can't have duplicate keys. In the long run, this should be fixed in torchtext; however, I haven't made that pull request yet.

The other commit adds `bos` and `eos` tokens to the source sequences. It seemed a little bit odd that they weren't present.

**Comment by bpopeters** [comment]
Including the `bos` and `eos` has an effect on the verbose output of translation.py, and that causes the tests to fail.

**Comment by srush** [comment]
Can you revert the part that breaks models? If you want that can be a separate PR.

**Comment by bpopeters** [comment]
@srush I removed the bits that were breaking the tests. However, I have a question: why don't the target sequences include bos and eos characters? They do in the Lua version, and if I want to replicate the conditions I have for my Lua experiments, being able to have the same vocab size would be nice.

The most recent batch of commits also clears the remaining hurdles in preprocessing/IO that made it impossible to use target features (they still don't work at translation time, but that has to do with some issues with Translator and the beam search that I haven't looked into).

This is mergeable, although there are still some things that I'd like to make nicer, like the stuff with `__dict__` and the rather awkward way we have to iterate over the `fields` dict to access the features.

**Comment by srush** [comment]
I think the target sequences do have eos and bos. Do you mean the source sequences? That may be a bug, let me look into it.

**Comment by srush** [comment]
Okay, I'm merging. More and more though, I think we should not be holding the whole dataset in disk. But let's do that separately.

**Comment by bpopeters** [comment]
Yes, after looking at it again it's the source sequences that don't have bos and eos.

I agree completely about storing the dataset in disk isn't a great idea and the I/O could use another look in general. It's seems to have gotten fairly complex, given the relative simplicity of taking two text files of the same length and turning it into aligned pairs of LongTensors. I would like to have another look at it, although at the moment I'm sprinting to the end of my MSc.

**Pull request merged**
