### PR TITLE
ConfigArgParse: Ability to use configfiles

### LINKED ISSUE #308: Add possibility to use config files
We should allow {preprocess,train,translate}.py files to take options from configs.

### PR DESCRIPTION
**Pull request by jerinphilip**
This more or less works - given the right configfile options.
* Code isn't PEP-8 passing yet - rest passes. 
* I tried autopep8, but it makes the code an unreadable mess.
* Train config options have a few issues, `decay_method` being empty is unable to be read due to some configargparse issue.
Fixes #308

### CODE REVIEW

**Comment by jerinphilip** [comment]
@JianyuZhan One test is failing, can you look and provide insights? Functionality is working at my end, BTW. :)

**Comment by JianyuZhan** [comment]
@jerinphilip,  Click the `Details` link above:https://travis-ci.org/OpenNMT/OpenNMT-py/jobs/287515696
Two errors reported:

1. `python -m unittest: error: argument -train_src/--train_src is required`
    `-train_src` doesn't pass in.

2.  

```
ERROR: test.test_preprocess (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test.test_preprocess
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/OpenNMT/OpenNMT-py/test/test_preprocess.py", line 14, in <module>
    opt = parser.parse_known_args()[0]
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/configargparse.py", line 556, in parse_known_args
    self, args=args, namespace=namespace)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/argparse.py", line 1957, in _parse_known_args
    self.error(_('argument %s is required') % name)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/argparse.py", line 2374, in error
    self.exit(2, _('%s: error: %s\n') % (self.prog, message))
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/argparse.py", line 2362, in exit
    _sys.exit(status)
SystemExit: 2
```

This again is some required argument doesn't pass in.  You might have changed something wrongly in `test_preprocess.py` ?

**Comment by jerinphilip** [comment]
No, you can take a look at the files changed - only `argparse` is substituted with `configargparse`.  Although I've modified the `preprocess_opts` function. That's probably what caused this.

Can you tell me the reason behind leaving a few arguments in the `preprocess.py` file, from your last commit?

**Comment by JianyuZhan** [comment]
The leftover options declaration is there for quite a long time.

I took a look at your code, I knew what caused the errors.

You move all options to `opts.py`, which I think is good!   But some of these options have `required` set to true,  so in `test/test_preprocess.py`:  https://github.com/OpenNMT/OpenNMT-py/blob/master/test/test_preprocess.py#L14, the parsing have problem, since you don't pass these `required` options to them.   

You should fix like this:

```
opt = parser.parse_known_args(['-train_src', 'data/src-train.txt',
                                                     '-train_tgt', 'data/tgt-train.txt'
                                                      .....])[0] 
```

**Comment by JianyuZhan** [comment]
Also one question,  why do we need a short version and a long version of options, e.g. `-train_src` and `--train_src`?   Is it required by `ConfigArgParse`?

**Comment by jerinphilip** [comment]
Yes, ConfigArgParse requirement is how I diagnosed it - was a quick fix attempt when things weren't working. I'll check once if it works without that as well.

**Comment by jerinphilip** [comment]
From [ConfigArgParse README](https://github.com/bw2/ConfigArgParse#special-values):

> Under the hood, configargparse handles environment variables and config file values by converting them to their corresponding command line arg. For example, "key = value" will be processed as if "--key value" was specified on the command line.

I guess that settles `--opt` thing.

**Comment by srush** [comment]
This looks good to me. Ready to merge?

**Comment by jerinphilip** [comment]
@srush @JianyuZhan: I'd like to add tests at some point if need be. You should know there are caveats - there are you a few empty arguments which create a problem when trying to parse in. 

Maybe this needs to be fixed in the ConfigArgParse end than here.
```ini
decay_method=
...
`
```
The above creates a problem since `decay_method` has to be in choices (`noam`) how ConfigArgParse reads it. In short, you can't use something written by `-save_config` unless you tweak the config file a little. Otherwise, this works. The above issue I found with `train.py` alone, the other two seemed to play nicely.

My method of testing was:
```bash
python <script.py> <args> -save_config <config_file>
python <script.py> -config <config_file>
```

The above can maybe added as a unit test - I'd have to learn a bit there.

**Comment by srush** [comment]
Oh, I see. That sounds like an issue on our end. Is it just arguments with choices? Or are there other things that break?

**Comment by jerinphilip** [comment]
@srush: I think this has to do with ConfigArgParser end. It fails when the `.ini` entry has an empty value, and it mistakes '=' as the value and then causes all sort of mess. I'll open an issue at ConfigArgParser repo - it is picking up '=' as value to key 'decay_method'.

```
train.py: error: argument -decay_method/--decay_method: invalid choice: '=' (choose from 'noam')
```

**Comment by JianyuZhan** [comment]
Hello, @jerinphilip, any progress so that we can make this merged? I think this feature is quite necessary to have.

**Pull request closed without merging**
