### PR TITLE
Fix some more lazy loading bugs

### PR DESCRIPTION
**Pull request by srush**
- Seemingly the old code only works for one iteration. Change the code so that it reinitializes the iteration each time and passes to train and test.

### CODE REVIEW

**Comment by JianyuZhan** [comment]
Ok. So the problem is the `DatasetLazyIter` only works for one epoch. Right?  

I think we can implement something like `repeat` as in `torchtext.data.Iterator`,  and we can reset to the initial status like `init_epoch()` in `torchtext.data.Iterator`.  So we can still keep the Trainer interface clean as before.

I will try to figure it out tomorrow.

**Comment by srush** [comment]
@JianyuZhan I am okay with the iterators being one epoch each. That interface makes more sense to me anyway, as it lets the client control differences between epochs. 

@vince62s I don't think that error is from this PR. I think it was possible a batch got too big. Can you try with a smaller `max_generator_batches` Also let me change the batch size to use the max of src and tgt.

**Comment by vince62s** [comment]
Also I think the max_shard_size in not very intuitive.
If I put 262144000 bytes I get .pt files of 1GB each

**Comment by srush** [comment]
It's input size not output size. It's pretty hard to predict output, but we can give an approximate multiplier

**Comment by JianyuZhan** [comment]
@srush Okay. I took a deep look at the current code, and yep, it makes sense.  I'll do a PR to do some cleanups.

**Pull request merged**
