### PR TITLE
Adding Bridge option

### PR DESCRIPTION
**Pull request by sebastianGehrmann**
This PR implements a bridge option that represents an additional linear layer between the last encoder state and the first decoder state.

### CODE REVIEW

**Comment by srush** [comment]
Think this is a real failure: 

```
1.48s$ python translate.py -model test/test_model2.pt  -src  data/morph/src.valid  -verbose -batch_size 10 -beam_size 10 -tgt data/morph/tgt.valid -out /tmp/trans; diff  data/morph/tgt.valid /tmp/trans
Loading model parameters.
Traceback (most recent call last):
  File "translate.py", line 141, in <module>
    main()
  File "translate.py", line 105, in main
    batch_data = translator.translate_batch(batch, data)
  File "/home/travis/build/OpenNMT/OpenNMT-py/onmt/translate/Translator.py", line 99, in translate_batch
    src, context, enc_states)
  File "/home/travis/build/OpenNMT/OpenNMT-py/onmt/Models.py", line 339, in init_decoder_state
    self._fix_enc_hidden(enc_hidden))
  File "/home/travis/build/OpenNMT/OpenNMT-py/onmt/Models.py", line 653, in __init__
    batch_size = context.size(1)
AttributeError: 'tuple' object has no attribute 'size'
```

**Comment by sebastianGehrmann** [comment]
Oh, I'm looking into this.

**Comment by srush** [comment]
Sorry, I think I caused a conflict as well with the name change PR.

**Comment by sebastianGehrmann** [comment]
Yea I just merged. The conflict wasn't too bad.

**Pull request merged**
