### PR TITLE
Fixing #394: save checkpoint with model_opt instead of opt

### PR DESCRIPTION
**Pull request by pltrdy**
(training is still bugged as mentioned in https://github.com/OpenNMT/OpenNMT-py/issues/400 we use the workaround is this issue to actually run it)

---

When we continue training we have two kind of arguments: 
* `opt`: directly from the command line
* `model_opt`: from the checkpoint

In standard training `opt == model_opt`. The model is created using `model_opt` settings i.e. that fits the checkpoint.

The problem is that we save checkpoints with `opt` dict. But at this point `opt` only contain default values.

### CODE REVIEW

**Comment by JianyuZhan** [comment]
I don't think this is a good way to fix.  The `NMTModel` should be agnostic to the `opt`, because `opt` is definitely not a parameter of model(the act of `model.opt = opt` would set it as parameter of model by  pytorch).

Since we now unify the `model_opt` with `opt` here:
https://github.com/OpenNMT/OpenNMT-py/blob/master/train.py#L271

In normal case, `model_opt` == `opt`.

In `train_from` case, the `opt` from command line should only change the gpu behavior(using gpu or not),   the reset of settings shall be restored from the `model_opt`(=`checkpoint['opt']`).

So the ideal way to fix this problem is to pass the `model_opt`  to `train_model()`,  and substitute all `opt` in `train_model()` with `model_opt`.  With this, we can correctly save checkpoint using `model_opt` without tinkering with `NMTModel`.

**Comment by pltrdy** [comment]
Alright. I wasn't sure it was a good thing to be honest, but I haven't found any good argument for not doing that way. 

I'll edit it, ty

**Comment by JianyuZhan** [comment]
Thanks, and one thing to note is https://github.com/OpenNMT/OpenNMT-py/blob/master/train.py#L277,
we now should modify the 'model_opt.start_epoch'.

**Comment by pltrdy** [comment]
Hmm, I don't see the problem with start_epoch, I haven't faced issues with it either

**Comment by JianyuZhan** [comment]
Well, my initial thought was to totally get rid of `opt` in `train_model()` and use `model_opt` instead, since we've unified `model_opt` and `opt` for both cases. And strictly speaking,  using `model_opt` in `train_from` case can avoid case in which users set a parameter in `opt` which has different value compared to the one in the checkpoint(`model_opt`).

**Comment by JianyuZhan** [comment]
@srush , sorry, I don't see what you request me to change ?

**Comment by srush** [comment]
Wait I don't understand. Do you guys both want this change?

**Comment by JianyuZhan** [comment]
I am okay with this change. @srush , you can merge.

**Comment by pltrdy** [comment]
Yes, sure. I'm currently using this code, it solved my issue.

**Comment by JianyuZhan** [comment]
@pltrdy ,  please update this PR to resolve the conflict for it to be merged.

**Pull request merged**
