### PR TITLE
Fix batch translation

### PR DESCRIPTION
**Pull request by srush**
Reverts OpenNMT/OpenNMT-py#413

### CODE REVIEW

**Comment by srush** [comment]
This is an unrevert of Guillaume's change, which seemed to cause a test failure

**Comment by guillaumekln** [comment]
I will take a look. Not sure why it fails now and not for the initial PR...

**Comment by srush** [comment]
I think this is my fault. I can look. It must have failed when I merged @sebastianGehrmann pr first.

**Comment by guillaumekln** [comment]
Yes, `GNMTGlobalScorer` (enabled by #409) produces `NaN` when the attention vector contains a 0 (which is the case with variable lengths source batch but could also happen otherwise).

**Comment by guillaumekln** [comment]
I fixed the issue by truncating the attention vectors passed to the beam code.

**Comment by srush** [comment]
thanks!

**Pull request merged**
