### PR TITLE
fixed src-feats parameter error for REST server and CTranslate2 models

### PR DESCRIPTION
**Pull request by cryptik**
Fixed the src-feats parameter error for REST server when using CTranslate2 models per @francoishernandez instructions and guidance.  I did run the check PR request script to verify there were no breaking changes.  Code was tested with CTranslate2 models and functions as expected.

### CODE REVIEW

**Comment by francoishernandez** [comment]
> Regarding the assert… it seems that when the translate() function is called, the caller is setting src_feats to {} (i.e. empty dict) rather than None or leaving the param out of the call. So my question is… should I add the assert so that both None and {} are permitted?

I think that's ok. We just want to check we don't have any features, because CT2 won't support it.

I'll merge. Thanks!

**Comment by francoishernandez** [comment]
@cryptik please merge latest master on your branch so the tests can run (#2144). Thanks!

**Comment by cryptik** [comment]
Ok, I think I did what you want.  I am a bit new to this kind of thing on GitHub.  I did a fetch&merge of master onto my feature-fix branch on cryptik/OpenNPT-py fork.

**Comment by francoishernandez** [comment]
Looks good, thanks!

**Pull request merged**
